##########################################################################
# 계좌정보 환경설정 (accno.ini)
##########################################################################
#	Comment: 설명
#	Aptype: Aptype의 대표값
#	Acc_No: 계좌번호
#	Pwd: login 비밀번호
#	Athrty: 사용자권한
#	Ip: IP address
#	Js_Band: 자동주문용지수선물번호
#	Jo_Band: 자동주문용지수옵션번호
#   주문번호 영역 처리방안 : 
#		전체사용영역    : 300,000번 부터 ~ 900,000번 까지사용
#		계좌당 사용영역 : Client :      1 ~ 10,000
#						  선물	 : 10,001 ~ 15,000
#						  옵션	 : 15,001 ~ 30,000
##########################################################################
# 선물옵션주문체결
##########################################################################
PA_CONF_START
Accno_Count=5

Accno_1_Comment=딜러01_현물
Accno_1_Aptype=31
Accno_1_Acc_No=999550101
Accno_1_Pwd=0000
Accno_1_Athrty=D31
Accno_1_Ip=172021101098
Accno_1_Auto_Man_Cnt=0110111111100000000000
Accno_1_Js_Band=315001
Accno_1_Risk_Max=-300000000
Accno_1_Acc_F_Order_MaxCnt=100
Accno_1_Acc_F_Get_MaxCnt=30
Accno_1_Acc_SO_Order_MaxCnt=100
Accno_1_Acc_SO_Get_MaxCnt=500
Accno_End

PA_CONF_END

##########################################################################
# End of File (accno.ini)
##########################################################################

