##########################################################################
# data SHM 정보 환경설정 (dshm.ini)
##########################################################################
#	dshm.ini는 real과 test가 동일함
#	Comment: 설명
#	Name: data SHM data name
#	Key: base key (4) + ',' + section (S:start, C:continue, E:end, O:one)
#		e.g. Key=0101,S -> PA (선물옵션주문체결)의 경우 data SHM segment의
#			key는 0x11010100고 해당 section은 segment의 시작부분임을 표시하며
#			여러 개의 process가 동시에 write할 경우 lock 처리를 위한 semaphore
#			의 key는 0x11010101이 됨
#-------------------------------------------------------------------------
#	* data SHM segment 및 semaphore의 key 구조
#	0x(1)(2)(3)(4)(5)(6)(7)(8) ->
#		(1)		- 2:PK system
#		(2)		- 1:Real, 2:Test
#		(3)(4)	- 부문. e.g. 01:PA, 02:PB, ..., 10:PJ, 11:PK, ...
#		(5)(6)	- 00:부문 SHM, 01~50:data SHM segment의 base key
#		(7)(8)	- 00:data SHM, 01~99:semaphore
#	e.g. 0x11010100 - PA (선물옵션주문체결), 선물옵션 data SHM
#		 0x11010101 - PA (선물옵션주문체결), 지수선물주문 data semaphore
#-------------------------------------------------------------------------
#	Fifo: FIFO count (equal to the number of processes that read this SHM)
#	Size: data size of a record
#		data size = size of a record - file header (62 bytes)
#						- data header (22) - LF (1)
#	Max: max record
##########################################################################
# 선물옵션주문체결
##########################################################################
PA_CONF_START
Dshm_Count=46

Dshm_1_Comment=유가주문송신01
Dshm_1_Name=pa_1101_ts
Dshm_1_Key=0101,S
Dshm_1_Fifo=1
Dshm_1_Size=261
Dshm_1_Max=10000
Dshm_End

Dshm_2_Comment=유가주문송신02
Dshm_2_Name=pa_1102_ts
Dshm_2_Key=0102,C
Dshm_2_Fifo=1
Dshm_2_Size=261
Dshm_2_Max=10000
Dshm_End

Dshm_3_Comment=코스닥주문송신01
Dshm_3_Name=pa_1111_ts
Dshm_3_Key=0103,C
Dshm_3_Fifo=1
Dshm_3_Size=261
Dshm_3_Max=10000
Dshm_End

Dshm_4_Comment=코스닥주문송신02
Dshm_4_Name=pa_1112_ts
Dshm_4_Key=0104,C
Dshm_4_Fifo=1
Dshm_4_Size=261
Dshm_4_Max=10000
Dshm_End

Dshm_5_Comment=파생주문송신01
Dshm_5_Name=pa_2101_ts
Dshm_5_Key=0105,C
Dshm_5_Fifo=1
Dshm_5_Size=261
Dshm_5_Max=10000
Dshm_End

Dshm_6_Comment=파생주문송신02
Dshm_6_Name=pa_2102_ts
Dshm_6_Key=0106,C
Dshm_6_Fifo=1
Dshm_6_Size=261
Dshm_6_Max=10000
Dshm_End

Dshm_7_Comment=자동주문0101
Dshm_7_Name=pa_50101mp
Dshm_7_Key=0107,C
Dshm_7_Fifo=1
Dshm_7_Size=2048
Dshm_7_Max=10000
Dshm_End

Dshm_8_Comment=자동주문0102
Dshm_8_Name=pa_50102mp
Dshm_8_Key=0108,C
Dshm_8_Fifo=1
Dshm_8_Size=2048
Dshm_8_Max=10000
Dshm_End

Dshm_9_Comment=자동주문0103
Dshm_9_Name=pa_50103mp
Dshm_9_Key=0109,C
Dshm_9_Fifo=1
Dshm_9_Size=2048
Dshm_9_Max=10000
Dshm_End

Dshm_10_Comment=자동주문0104
Dshm_10_Name=pa_50104mp
Dshm_10_Key=0110,C
Dshm_10_Fifo=1
Dshm_10_Size=2048
Dshm_10_Max=10000
Dshm_End

Dshm_11_Comment=자동주문0105
Dshm_11_Name=pa_50105mp
Dshm_11_Key=0111,C
Dshm_11_Fifo=1
Dshm_11_Size=2048
Dshm_11_Max=10000
Dshm_End

Dshm_12_Comment=자동주문0106
Dshm_12_Name=pa_50106mp
Dshm_12_Key=0112,C
Dshm_12_Fifo=1
Dshm_12_Size=2048
Dshm_12_Max=10000
Dshm_End

Dshm_13_Comment=자동주문0107
Dshm_13_Name=pa_50107mp
Dshm_13_Key=0113,C
Dshm_13_Fifo=1
Dshm_13_Size=2048
Dshm_13_Max=10000
Dshm_End

Dshm_14_Comment=자동주문0108
Dshm_14_Name=pa_50108mp
Dshm_14_Key=0114,C
Dshm_14_Fifo=1
Dshm_14_Size=2048
Dshm_14_Max=10000
Dshm_End

Dshm_15_Comment=자동주문0109
Dshm_15_Name=pa_50109mp
Dshm_15_Key=0115,C
Dshm_15_Fifo=1
Dshm_15_Size=2048
Dshm_15_Max=10000
Dshm_End

Dshm_16_Comment=자동주문0110
Dshm_16_Name=pa_50110mp
Dshm_16_Key=0116,C
Dshm_16_Fifo=1
Dshm_16_Size=2048
Dshm_16_Max=10000
Dshm_End

Dshm_17_Comment=자동주문0201
Dshm_17_Name=pa_50201mp
Dshm_17_Key=0117,C
Dshm_17_Fifo=1
Dshm_17_Size=2048
Dshm_17_Max=10000
Dshm_End

Dshm_18_Comment=자동주문0202
Dshm_18_Name=pa_50202mp
Dshm_18_Key=0118,C
Dshm_18_Fifo=1
Dshm_18_Size=2048
Dshm_18_Max=10000
Dshm_End

Dshm_19_Comment=자동주문0203
Dshm_19_Name=pa_50203mp
Dshm_19_Key=0119,C
Dshm_19_Fifo=1
Dshm_19_Size=2048
Dshm_19_Max=10000
Dshm_End

Dshm_20_Comment=자동주문0204
Dshm_20_Name=pa_50204mp
Dshm_20_Key=0120,C
Dshm_20_Fifo=1
Dshm_20_Size=2048
Dshm_20_Max=10000
Dshm_End

Dshm_21_Comment=자동주문0205
Dshm_21_Name=pa_50205mp
Dshm_21_Key=0121,C
Dshm_21_Fifo=1
Dshm_21_Size=2048
Dshm_21_Max=10000
Dshm_End

Dshm_22_Comment=자동주문0206
Dshm_22_Name=pa_50206mp
Dshm_22_Key=0122,C
Dshm_22_Fifo=1
Dshm_22_Size=2048
Dshm_22_Max=10000
Dshm_End

Dshm_23_Comment=자동주문0207
Dshm_23_Name=pa_50207mp
Dshm_23_Key=0123,C
Dshm_23_Fifo=1
Dshm_23_Size=2048
Dshm_23_Max=10000
Dshm_End

Dshm_24_Comment=자동주문0208
Dshm_24_Name=pa_50208mp
Dshm_24_Key=0124,C
Dshm_24_Fifo=1
Dshm_24_Size=2048
Dshm_24_Max=10000
Dshm_End

Dshm_25_Comment=자동주문0209
Dshm_25_Name=pa_50209mp
Dshm_25_Key=0125,C
Dshm_25_Fifo=1
Dshm_25_Size=2048
Dshm_25_Max=10000
Dshm_End

Dshm_26_Comment=자동주문0210
Dshm_26_Name=pa_50210mp
Dshm_26_Key=0126,C
Dshm_26_Fifo=1
Dshm_26_Size=2048
Dshm_26_Max=10000
Dshm_End

Dshm_27_Comment=자동주문0301
Dshm_27_Name=pa_50301mp
Dshm_27_Key=0127,C
Dshm_27_Fifo=1
Dshm_27_Size=2048
Dshm_27_Max=10000
Dshm_End

Dshm_28_Comment=자동주문0302
Dshm_28_Name=pa_50302mp
Dshm_28_Key=0128,C
Dshm_28_Fifo=1
Dshm_28_Size=2048
Dshm_28_Max=10000
Dshm_End

Dshm_29_Comment=자동주문0303
Dshm_29_Name=pa_50303mp
Dshm_29_Key=0129,C
Dshm_29_Fifo=1
Dshm_29_Size=2048
Dshm_29_Max=10000
Dshm_End

Dshm_30_Comment=자동주문0304
Dshm_30_Name=pa_50304mp
Dshm_30_Key=0130,C
Dshm_30_Fifo=1
Dshm_30_Size=2048
Dshm_30_Max=10000
Dshm_End

Dshm_31_Comment=자동주문0305
Dshm_31_Name=pa_50305mp
Dshm_31_Key=0131,C
Dshm_31_Fifo=1
Dshm_31_Size=2048
Dshm_31_Max=10000
Dshm_End

Dshm_32_Comment=자동주문0306
Dshm_32_Name=pa_50306mp
Dshm_32_Key=0132,C
Dshm_32_Fifo=1
Dshm_32_Size=2048
Dshm_32_Max=10000
Dshm_End

Dshm_33_Comment=자동주문0307
Dshm_33_Name=pa_50307mp
Dshm_33_Key=0133,C
Dshm_33_Fifo=1
Dshm_33_Size=2048
Dshm_33_Max=10000
Dshm_End

Dshm_34_Comment=자동주문0308
Dshm_34_Name=pa_50308mp
Dshm_34_Key=0134,C
Dshm_34_Fifo=1
Dshm_34_Size=2048
Dshm_34_Max=10000
Dshm_End

Dshm_35_Comment=자동주문0309
Dshm_35_Name=pa_50309mp
Dshm_35_Key=0135,C
Dshm_35_Fifo=1
Dshm_35_Size=2048
Dshm_35_Max=10000
Dshm_End

Dshm_36_Comment=자동주문0310
Dshm_36_Name=pa_50310mp
Dshm_36_Key=0136,C
Dshm_36_Fifo=1
Dshm_36_Size=2048
Dshm_36_Max=10000
Dshm_End

Dshm_37_Comment=자동주문0401
Dshm_37_Name=pa_50401mp
Dshm_37_Key=0137,C
Dshm_37_Fifo=1
Dshm_37_Size=2048
Dshm_37_Max=10000
Dshm_End

Dshm_38_Comment=자동주문0402
Dshm_38_Name=pa_50402mp
Dshm_38_Key=0138,C
Dshm_38_Fifo=1
Dshm_38_Size=2048
Dshm_38_Max=10000
Dshm_End

Dshm_39_Comment=자동주문0403
Dshm_39_Name=pa_50403mp
Dshm_39_Key=0139,C
Dshm_39_Fifo=1
Dshm_39_Size=2048
Dshm_39_Max=10000
Dshm_End

Dshm_40_Comment=자동주문0404
Dshm_40_Name=pa_50404mp
Dshm_40_Key=0140,C
Dshm_40_Fifo=1
Dshm_40_Size=2048
Dshm_40_Max=10000
Dshm_End

Dshm_41_Comment=자동주문0405
Dshm_41_Name=pa_50405mp
Dshm_41_Key=0141,C
Dshm_41_Fifo=1
Dshm_41_Size=2048
Dshm_41_Max=10000
Dshm_End

Dshm_42_Comment=자동주문0406
Dshm_42_Name=pa_50406mp
Dshm_42_Key=0142,C
Dshm_42_Fifo=1
Dshm_42_Size=2048
Dshm_42_Max=10000
Dshm_End

Dshm_43_Comment=자동주문0407
Dshm_43_Name=pa_50407mp
Dshm_43_Key=0143,C
Dshm_43_Fifo=1
Dshm_43_Size=2048
Dshm_43_Max=10000
Dshm_End

Dshm_44_Comment=자동주문0408
Dshm_44_Name=pa_50408mp
Dshm_44_Key=0144,C
Dshm_44_Fifo=1
Dshm_44_Size=2048
Dshm_44_Max=10000
Dshm_End

Dshm_45_Comment=자동주문0409
Dshm_45_Name=pa_50409mp
Dshm_45_Key=0145,C
Dshm_45_Fifo=1
Dshm_45_Size=2048
Dshm_45_Max=10000
Dshm_End

Dshm_46_Comment=자동주문0410
Dshm_46_Name=pa_50410mp
Dshm_46_Key=0146,E
Dshm_46_Fifo=1
Dshm_46_Size=2048
Dshm_46_Max=10000
Dshm_End

PA_CONF_END

##########################################################################
# End of File (dshm.ini)
##########################################################################

