#########################################################################
# FILE 정보 환경설정 (file.ini)
##########################################################################
#	file.ini는 real과 test가 동일함
#	Name: SAM file name
#	Fifo: FIFO count (equal to the number of processes that read this file)
#	Size: data size of a record (one line in a file is a record)
#		data size = size of a record - file header (62 bytes)
#			- data header (22) - LF (1)
##########################################################################
# HATS_Basic
##########################################################################
PA_CONF_START
File_Count=104

File_1_Comment=현물주문응답
File_1_Name=pa_1201_mp
File_1_Fifo=2
File_1_Size=500
File_End

File_2_Comment=현물체결
File_2_Name=pa_1401_mp
File_2_Fifo=2
File_2_Size=500
File_End

File_3_Comment=파생주문응답
File_3_Name=pa_2201_mp
File_3_Fifo=2
File_3_Size=500
File_End

File_4_Comment=파생체결
File_4_Name=pa_2401_mp
File_4_Fifo=2
File_4_Size=500
File_End

File_5_Comment=KSP_Markert_Info
File_5_Name=pa_1601_mp
File_5_Fifo=1
File_5_Size=200
File_End

File_6_Comment=KSD_Markert_Info
File_6_Name=pa_1611_mp
File_6_Fifo=1
File_6_Size=200
File_End

File_7_Comment=DEV_Markert_Info
File_7_Name=pa_2601_mp
File_7_Fifo=1
File_7_Size=200
File_End

File_8_Comment=조회요구
File_8_Name=pa_6001_mp
File_8_Fifo=1
File_8_Size=2048
File_End

File_9_Comment=Client송신
File_9_Name=pa_8101_ts
File_9_Fifo=2
File_9_Size=2048
File_End

#시세 AUTO 활용
File_10_Comment=해외CME_Auto(체결반응)
File_10_Name=pa_6102_ur
File_10_Fifo=1
File_10_Size=1
File_End

File_11_Comment=해외SGX_Auto(체결반응)
File_11_Name=pa_6302_ur
File_11_Fifo=1
File_11_Size=1
File_End

File_12_Comment=해외EUX_Auto(체결반응)
File_12_Name=pa_6402_ur
File_12_Fifo=1
File_12_Size=1
File_End

File_13_Comment=해외HKG_Auto(체결반응)
File_13_Name=pa_6502_ur
File_13_Fifo=1
File_13_Size=1
File_End

File_14_Comment=지수선물Auto용(체결반응)
File_14_Name=pa_7111_ur
File_14_Fifo=1
File_14_Size=1
File_End

File_15_Comment=지수옵션Auto용(체결반응)
File_15_Name=pa_7211_ur
File_15_Fifo=1
File_15_Size=1
File_End

File_16_Comment=개별선물Auto용(체결반응)
File_16_Name=pa_7311_ur
File_16_Fifo=1
File_16_Size=1
File_End

File_17_Comment=개별옵션Auto용(체결반응)
File_17_Name=pa_7411_ur
File_17_Fifo=1
File_17_Size=1
File_End

File_18_Comment=K300Auto용(체결반응)
File_18_Name=pa_7811_ur
File_18_Fifo=1
File_18_Size=1
File_End

File_19_Comment=K150FAuto용(체결반응)
File_19_Name=pa_7911_ur
File_19_Fifo=1
File_19_Size=1
File_End

File_20_Comment=K150OAuto용(체결반응)
File_20_Name=pa_7912_ur
File_20_Fifo=1
File_20_Size=1
File_End

File_21_Comment=유가증권Auto용(체결반응)
File_21_Name=pa_7511_ur
File_21_Fifo=1
File_21_Size=1
File_End

File_22_Comment=코스닥Auto용(체결반응)
File_22_Name=pa_7611_ur
File_22_Fifo=1
File_22_Size=1
File_End

File_23_Comment=ELW_Auto용(체결반응)
File_23_Name=pa_7711_ur
File_23_Fifo=1
File_23_Size=1
File_End

File_24_Comment=직결미니선물용(체결반응)
File_24_Name=pa_7915_ur
File_24_Fifo=1
File_24_Size=1
File_End

File_25_Comment=직결미니옵션용(체결반응)
File_25_Name=pa_7916_ur
File_25_Fifo=1
File_25_Size=1
File_End

File_26_Comment=미니선물용(체결반응)
File_26_Name=pa_6511_ur
File_26_Fifo=1
File_26_Size=1
File_End

File_27_Comment=미니옵션용(체결반응)
File_27_Name=pa_6611_ur
File_27_Fifo=1
File_27_Size=1
File_End

File_28_Comment=지수정보(체결반응)
File_28_Name=pa_7011_ur
File_28_Fifo=1
File_28_Size=1
File_End

File_29_Comment=전체시세
File_29_Name=pa_7001_mp
File_29_Fifo=1
File_29_Size=800
File_End

#	시세수신처리
File_30_Comment=지수정보
File_30_Name=pa_7001_dd
File_30_Fifo=1
File_30_Size=50
File_End

File_31_Comment=지수선물기본
File_31_Name=pa_7101_dd
File_31_Fifo=1
File_31_Size=1300
File_End

File_32_Comment=지수선물시세
File_32_Name=pa_7111_dd
File_32_Fifo=1
File_32_Size=300
File_End

File_33_Comment=지수옵션기본
File_33_Name=pa_7201_dd
File_33_Fifo=1
File_33_Size=1300
File_End

File_34_Comment=지수옵션시세(CALL)
File_34_Name=pa_7211_dd
File_34_Fifo=1
File_34_Size=300
File_End

File_35_Comment=지수옵션시세(PUT)
File_35_Name=pa_7212_dd
File_35_Fifo=1
File_35_Size=300
File_End

File_36_Comment=개별선물기본
File_36_Name=pa_7301_dd
File_36_Fifo=1
File_36_Size=1300
File_End

File_37_Comment=개별선물시세
File_37_Name=pa_7311_dd
File_37_Fifo=1
File_37_Size=550
File_End

File_38_Comment=개별옵션기본
File_38_Name=pa_7401_dd
File_38_Fifo=1
File_38_Size=1300
File_End

File_39_Comment=개별옵션시세01
File_39_Name=pa_7411_dd
File_39_Fifo=1
File_39_Size=550
File_End

File_40_Comment=개별옵션시세02
File_40_Name=pa_7412_dd
File_40_Fifo=1
File_40_Size=550
File_End

#202201 S
File_41_Comment=KRX300기본
File_41_Name=pa_7801_dd
File_41_Fifo=1
File_41_Size=1300
File_End

File_42_Comment=KRX300시세
File_42_Name=pa_7811_dd
File_42_Fifo=1
File_42_Size=350
File_End

File_43_Comment=K150F기본
File_43_Name=pa_7901_dd
File_43_Fifo=1
File_43_Size=1300
File_End

File_44_Comment=K150F시세
File_44_Name=pa_7911_dd
File_44_Fifo=1
File_44_Size=350
File_End

File_45_Comment=K150O기본
File_45_Name=pa_7902_dd
File_45_Fifo=1
File_45_Size=1300
File_End

File_46_Comment=K150O시세
File_46_Name=pa_7912_dd
File_46_Fifo=1
File_46_Size=350
File_End

File_47_Comment=MINIF기본
File_47_Name=pa_7905_dd
File_47_Fifo=1
File_47_Size=1300
File_End

File_48_Comment=MINIF시세
File_48_Name=pa_7915_dd
File_48_Fifo=1
File_48_Size=350
File_End

File_49_Comment=MINIO기본
File_49_Name=pa_7906_dd
File_49_Fifo=1
File_49_Size=1300
File_End

File_50_Comment=MINIO시세
File_50_Name=pa_7916_dd
File_50_Fifo=1
File_50_Size=350
File_End

#202201 E

File_51_Comment=유가증권기본
File_51_Name=pa_7501_dd
File_51_Fifo=1
File_51_Size=910
File_End

File_52_Comment=유가증권S1기본
File_52_Name=pa_7502_dd
File_52_Fifo=1
File_52_Size=160
File_End

File_53_Comment=유가증권체결01
File_53_Name=pa_7511_dd
File_53_Fifo=1
File_53_Size=160
File_End

File_54_Comment=유가증권체결02
File_54_Name=pa_7512_dd
File_54_Fifo=1
File_54_Size=160
File_End

File_55_Comment=유가증권호가01
File_55_Name=pa_7521_dd
File_55_Fifo=1
File_55_Size=800
File_End

File_56_Comment=유가증권호가02
File_56_Name=pa_7522_dd
File_56_Fifo=1
File_56_Size=800
File_End

File_57_Comment=코스닥기본수신
File_57_Name=pa_7601_dd
File_57_Fifo=1
File_57_Size=800
File_End

File_58_Comment=코스닥체결01
File_58_Name=pa_7611_dd
File_58_Fifo=1
File_58_Size=160
File_End

File_59_Comment=코스닥체결02
File_59_Name=pa_7612_dd
File_59_Fifo=1
File_59_Size=160
File_End

File_60_Comment=코스닥호가01
File_60_Name=pa_7621_dd
File_60_Fifo=1
File_60_Size=560
File_End

File_61_Comment=코스닥호가02
File_61_Name=pa_7622_dd
File_61_Fifo=1
File_61_Size=560
File_End

File_62_Comment=ELW체결01
File_62_Name=pa_7711_dd
File_62_Fifo=1
File_62_Size=160
File_End

File_63_Comment=ELW체결02
File_63_Name=pa_7712_dd
File_63_Fifo=1
File_63_Size=160
File_End

File_64_Comment=ELW호가01
File_64_Name=pa_7721_dd
File_64_Fifo=1
File_64_Size=800
File_End

File_65_Comment=ELW호가02
File_65_Name=pa_7722_dd
File_65_Fifo=1
File_65_Size=800
File_End

File_66_Comment=한도자동로직관리
File_66_Name=pa_9001_mp
File_66_Fifo=1
File_66_Size=2048
File_End

###################################################################
# 파생시장 내부포트용 (잠시사용)
###################################################################
File_67_Comment=지수선물A0
File_67_Name=pa_7191_dd
File_67_Fifo=1
File_67_Size=1300
File_End

File_68_Comment=지수선물B6
File_68_Name=pa_7192_dd
File_68_Fifo=1
File_68_Size=300
File_End

File_69_Comment=지수선물A3G7M4
File_69_Name=pa_7193_dd
File_69_Fifo=1
File_69_Size=300
File_End

File_70_Comment=지수옵션A0
File_70_Name=pa_7291_dd
File_70_Fifo=1
File_70_Size=1300
File_End

File_71_Comment=지수옵션B6
File_71_Name=pa_7292_dd
File_71_Fifo=1
File_71_Size=300
File_End

File_72_Comment=지수옵션A3G7M4
File_72_Name=pa_7293_dd
File_72_Fifo=1
File_72_Size=300
File_End

File_73_Comment=주식선물시세
File_73_Name=pa_7391_dd
File_73_Fifo=1
File_73_Size=1300
File_End

File_74_Comment=주식선물시세
File_74_Name=pa_7392_dd
File_74_Fifo=1
File_74_Size=550
File_End

File_75_Comment=주식옵션시세
File_75_Name=pa_7491_dd
File_75_Fifo=1
File_75_Size=1300
File_End

File_76_Comment=주식옵션시세
File_76_Name=pa_7492_dd
File_76_Fifo=1
File_76_Size=550
File_End

File_77_Comment=K300시세
File_77_Name=pa_7891_dd
File_77_Fifo=1
File_77_Size=1300
File_End

File_78_Comment=K300시세
File_78_Name=pa_7892_dd
File_78_Fifo=1
File_78_Size=300
File_End

File_79_Comment=K150F시세
File_79_Name=pa_7991_dd
File_79_Fifo=1
File_79_Size=1300
File_End

File_80_Comment=K150F시세
File_80_Name=pa_7996_dd
File_80_Fifo=1
File_80_Size=320
File_End

File_81_Comment=K150O시세
File_81_Name=pa_7992_dd
File_81_Fifo=1
File_81_Size=1300
File_End

File_82_Comment=K150O시세
File_82_Name=pa_7997_dd
File_82_Fifo=1
File_82_Size=300
File_End

File_83_Comment=미니선물시세
File_83_Name=pa_6591_dd
File_83_Fifo=1
File_83_Size=1300
File_End

File_84_Comment=미니선물시세
File_84_Name=pa_6592_dd
File_84_Fifo=1
File_84_Size=300
File_End

File_85_Comment=미니옵션시세
File_85_Name=pa_6691_dd
File_85_Fifo=1
File_85_Size=1300
File_End

File_86_Comment=미니옵션시세
File_86_Name=pa_6692_dd
File_86_Fifo=1
File_86_Size=300
File_End

File_87_Comment=FCME_정산
File_87_Name=pa_6100_dd
File_87_Fifo=1
File_87_Size=100
File_End

File_88_Comment=FCME_MASTER
File_88_Name=pa_6101_dd
File_88_Fifo=1
File_88_Size=400
File_End

File_89_Comment=FCME_시세01
File_89_Name=pa_6102_dd
File_89_Fifo=1
File_89_Size=450
File_End

File_90_Comment=FCME_시세02
File_90_Name=pa_6103_dd
File_90_Fifo=1
File_90_Size=450
File_End

File_91_Comment=FCME_시세03
File_91_Name=pa_6104_dd
File_91_Fifo=1
File_91_Size=450
File_End

File_92_Comment=FCME_시세04
File_92_Name=pa_6105_dd
File_92_Fifo=1
File_92_Size=450
File_End

File_93_Comment=FCME_시세05
File_93_Name=pa_6106_dd
File_93_Fifo=1
File_93_Size=450
File_End

File_94_Comment=FCME_시세06
File_94_Name=pa_6107_dd
File_94_Fifo=1
File_94_Size=450
File_End

File_95_Comment=FCMX_시세01
File_95_Name=pa_6202_dd
File_95_Fifo=1
File_95_Size=450
File_End

File_96_Comment=FSGX_정산
File_96_Name=pa_6300_dd
File_96_Fifo=1
File_96_Size=100
File_End

File_97_Comment=FSGX_MASTER
File_97_Name=pa_6301_dd
File_97_Fifo=1
File_97_Size=400
File_End

File_98_Comment=FSGX_시세01
File_98_Name=pa_6302_dd
File_98_Fifo=1
File_98_Size=450
File_End

File_99_Comment=FEUX_정산
File_99_Name=pa_6400_dd
File_99_Fifo=1
File_99_Size=100
File_End

File_100_Comment=FEUX_MASTER
File_100_Name=pa_6401_dd
File_100_Fifo=1
File_100_Size=400
File_End

File_101_Comment=FEUX_시세01
File_101_Name=pa_6402_dd
File_101_Fifo=1
File_101_Size=450
File_End

File_102_Comment=FHKG_정산
File_102_Name=pa_6500_dd
File_102_Fifo=1
File_102_Size=100
File_End

File_103_Comment=FHKG_MASTER
File_103_Name=pa_6501_dd
File_103_Fifo=1
File_103_Size=400
File_End

File_104_Comment=FHKG_시세01
File_104_Name=pa_6502_dd
File_104_Fifo=1
File_104_Size=450
File_End

PA_CONF_END

##########################################################################
# End of File (file.ini)
##########################################################################

