##########################################################################
# 시세 TR 정보 환경 설정 (sisetr.ini)
##########################################################################
#	Comment: 설명 (max 40 bytes)
#	Tr: 시세 TR code
#	Length: UDP 수신 전문 길이 (0xff 포함)
#	Queue: 업무구분 
#   (0:미사용 TR, 1:지수선물, 2:지수옵션, 3: 주식선물, 4: 주식옵션, 
#	 5:유가증권, 6:코스닥, 7:ELW, 8:ETF, 9:ETN, 10:지수)
##########################################################################
###########################################################################
# TR별 시세 분류 코드
###########################################################################
PA_CONF_START
Sise_Count=30

# ############# #
# 유가증권 시세 #
# ############# #
Sise_1_Comment=종목정보
Sise_1_Tr=A0011
Sise_1_Length=800
Sise_1_Queue=5
Sise_End

Sise_2_Comment=체결
Sise_2_Tr=A3011
Sise_2_Length=160
Sise_2_Queue=5
Sise_End

Sise_3_Comment=호가
Sise_3_Tr=B6011
Sise_3_Length=560
Sise_3_Queue=5
Sise_End

# ########### #
# 코스닥 시세 #
# ########### #
Sise_4_Comment=종목정보
Sise_4_Tr=A0012
Sise_4_Length=800
Sise_4_Queue=5
Sise_End

Sise_5_Comment=체결
Sise_5_Tr=A3012
Sise_5_Length=160
Sise_5_Queue=5
Sise_End

Sise_6_Comment=호가
Sise_6_Tr=B6012
Sise_6_Length=560
Sise_6_Queue=5
Sise_End

# ######### #
# 지수 시세 #
# ######### #
Sise_7_Comment=KRX100지수
Sise_7_Tr=C8011
Sise_7_Length=50
Sise_7_Queue=10
Sise_End

Sise_8_Comment=KOSPI지수
Sise_8_Tr=D0011
Sise_8_Length=50
Sise_8_Queue=10
Sise_End

Sise_9_Comment=KOSPI200지수
Sise_9_Tr=D2011
Sise_9_Length=50
Sise_9_Queue=10
Sise_End

# ######## #
# ELW 시세 #
# ######## #
Sise_10_Comment=종목정보(ELW)
Sise_10_Tr=A1011
Sise_10_Length=910
Sise_10_Queue=3
Sise_End

Sise_11_Comment=LP정보
Sise_11_Tr=I7011
Sise_11_Length=250
Sise_11_Queue=3
Sise_End

Sise_12_Comment=ELW체결
Sise_12_Tr=A3021
Sise_12_Length=160
Sise_12_Queue=3
Sise_End

Sise_13_Comment=ELW호가잔량(LP포함)
Sise_13_Tr=B7021
Sise_13_Length=800
Sise_13_Queue=3
Sise_End

###########################################################################
# 지수선물옵션 시세 분류 코드
###########################################################################
Sise_14_Comment=종목배치
Sise_14_Tr=A0014
Sise_14_Length=1300
Sise_14_Queue=1
Sise_End

Sise_15_Comment=체결
Sise_15_Tr=A3014
Sise_15_Length=117
Sise_15_Queue=1
Sise_End

Sise_16_Comment=우선호가
Sise_16_Tr=B6014
Sise_16_Length=220
Sise_16_Queue=1
Sise_End

Sise_17_Comment=체결/우선호가
Sise_17_Tr=G7014
Sise_17_Length=299
Sise_17_Queue=1
Sise_End

Sise_18_Comment=종목배치
Sise_18_Tr=A0034
Sise_18_Length=1300
Sise_18_Queue=2
Sise_End

Sise_19_Comment=체결
Sise_19_Tr=A3034
Sise_19_Length=104
Sise_19_Queue=2
Sise_End

Sise_20_Comment=우선호가
Sise_20_Tr=B6034
Sise_20_Length=223
Sise_20_Queue=2
Sise_End

Sise_21_Comment=체결/우선호가
Sise_21_Tr=G7034
Sise_21_Length=288
Sise_21_Queue=2
Sise_End

###########################################################################
# 주식선물옵션 시세 분류 코드
###########################################################################
Sise_22_Comment=종목배치
Sise_22_Tr=A0015
Sise_22_Length=1300
Sise_22_Queue=3
Sise_End

Sise_23_Comment=체결
Sise_23_Tr=A3015
Sise_23_Length=113
Sise_23_Queue=3
Sise_End

Sise_24_Comment=우선호가
Sise_24_Tr=B6015
Sise_24_Length=448
Sise_24_Queue=3
Sise_End

Sise_25_Comment=체결/우선호가
Sise_25_Tr=G7015
Sise_25_Length=539
Sise_25_Queue=3
Sise_End

Sise_26_Comment=종목배치
Sise_26_Tr=A0025
Sise_26_Length=1300
Sise_26_Queue=4
Sise_End

Sise_27_Comment=체결
Sise_27_Tr=A3025
Sise_27_Length=114
Sise_27_Queue=4
Sise_End

Sise_28_Comment=우선호가
Sise_28_Tr=B6025
Sise_28_Length=448
Sise_28_Queue=4
Sise_End

Sise_29_Comment=체결/우선호가
Sise_29_Tr=G7025
Sise_29_Length=520
Sise_29_Queue=4
Sise_End

PA_CONF_END

##########################################################################
# End of File (sisetr.ini)
##########################################################################

