##########################################################################
# TCP2 (직접접속 방식) 정보 환경 설정 (tcp2.ini)
##########################################################################
#	Ip: server ip address
#		All numbers supplied as parts in dot notation can be decimal, octal,
#		or hexadecimal, as specified in the C language (i.e., a leading 0x or
#		0X implies hexadecimal; a leading 0 implies octal; otherwise, the
#		number is interpreted as decimal).
#		e.g. 172.30.220.151 (correct), 172.030.220.151 (false)
#	Dup_Id: avoiding duplication of port
#	Port: port number
##########################################################################
# HATS_B (PA)
##########################################################################
PA_CONF_START
Tcp2_Count=7

Tcp2_1_Comment=현물주문_FEP(주문TEST)
Tcp2_1_Ip=172.17.201.73
Tcp2_1_Dup_Id=0
Tcp2_1_Port=31000
Tcp2_End

Tcp2_2_Comment=파생주문_FEP(체결TEST)
Tcp2_2_Ip=172.17.201.71
Tcp2_2_Dup_Id=1
Tcp2_2_Port=31000
Tcp2_End

Tcp2_3_Comment=공개장운영_FEP(장운영TEST)
Tcp2_3_Ip=172.17.225.131
Tcp2_3_Dup_Id=2
Tcp2_3_Port=31000
Tcp2_End

Tcp2_4_Comment=_Client(송신)SVR
Tcp2_4_Ip=0.0.0.0
Tcp2_4_Dup_Id=0
Tcp2_4_Port=32001
Tcp2_End

Tcp2_5_Comment=_Client(수신)_SVR
Tcp2_5_Ip=0.0.0.0
Tcp2_5_Dup_Id=0
Tcp2_5_Port=32011
Tcp2_End

Tcp2_6_Comment=_Client(송신)SVR2
Tcp2_6_Ip=0.0.0.0
Tcp2_6_Dup_Id=0
Tcp2_6_Port=32002
Tcp2_End

Tcp2_7_Comment=_Client(수신)_SVR2
Tcp2_7_Ip=0.0.0.0
Tcp2_7_Dup_Id=0
Tcp2_7_Port=32012
Tcp2_End

PA_CONF_END

##########################################################################
# End of File (tcp2.ini)
##########################################################################
