##########################################################################
# UDPIP 정보 환경 설정 (udpip.ini)
##########################################################################
#	Comment: 설명 (max 40 bytes)
#	Ip_1 ~ Ip_20: server ip address
#		All numbers supplied as parts in dot notation can be decimal, octal,
#		or hexadecimal, as specified in the C language (i.e., a leading 0x or
#		0X implies hexadecimal; a leading 0 implies octal; otherwise, the
#		number is interpreted as decimal).
#		e.g. 172.30.220.151 (correct), 172.030.220.151 (false)
#	Dup_Id: avoiding duplication of port
#	Port_1 ~ Port_20: server port number
##########################################################################
# 선물옵션주문체결
##########################################################################
PA_CONF_START
Udpip_Count=67

Udpip_1_Comment=지수선물기본수신
Udpip_1_Ip_1=233.37.54.191
Udpip_1_Port_1=15571
Udpip_End

Udpip_2_Comment=지수선물시세수신
Udpip_2_Ip_1=233.37.54.171
Udpip_2_Port_1=15572
Udpip_End

Udpip_3_Comment=지수옵션기본수신
Udpip_3_Ip_1=233.37.54.195
Udpip_3_Port_1=15511
Udpip_End

Udpip_4_Comment=지수옵션시세(CALL)수신
Udpip_4_Ip_1=233.37.54.161
Udpip_4_Port_1=15515
Udpip_End

Udpip_5_Comment=지수옵션시세(PUT)수신
Udpip_5_Ip_1=233.37.54.162
Udpip_5_Port_1=15516
Udpip_End

Udpip_6_Comment=주식선물기본수신
Udpip_6_Ip_1=233.37.54.193
Udpip_6_Port_1=15591
Udpip_End

Udpip_7_Comment=주식선물시세수신
Udpip_7_Ip_1=233.37.54.174
Udpip_7_Port_1=15592
Udpip_End

Udpip_8_Comment=주식옵션기본수신
Udpip_8_Ip_1=233.37.54.197
Udpip_8_Port_1=15521
Udpip_End

Udpip_9_Comment=주식옵션시세(1G)수신
Udpip_9_Ip_1=233.37.54.175
Udpip_9_Port_1=15522
Udpip_End

Udpip_10_Comment=주식옵션시세(2G)수신
Udpip_10_Ip_1=233.37.54.175
Udpip_10_Port_1=15523
Udpip_End

#202201 S
Udpip_11_Comment=KRX300기본수신
Udpip_11_Ip_1=233.37.54.184
Udpip_11_Port_1=15371
Udpip_End

Udpip_12_Comment=KRX300시세수신
Udpip_12_Ip_1=233.37.54.184
Udpip_12_Port_1=15372
Udpip_End

Udpip_13_Comment=K150F기본수신
Udpip_13_Ip_1=233.37.54.192
Udpip_13_Port_1=15581
Udpip_End

Udpip_14_Comment=K150F시세수신
Udpip_14_Ip_1=233.37.54.172
Udpip_14_Port_1=15582
Udpip_End

Udpip_15_Comment=K150O기본수신
Udpip_15_Ip_1=233.37.54.185
Udpip_15_Port_1=15391
Udpip_End

Udpip_16_Comment=K150O시세수신
Udpip_16_Ip_1=233.37.54.185
Udpip_16_Port_1=15392
Udpip_End

Udpip_17_Comment=MINIF기본수신
Udpip_17_Ip_1=233.37.54.245
Udpip_17_Port_1=15351
Udpip_End

Udpip_18_Comment=MINIF시세수신
Udpip_18_Ip_1=233.37.54.245
Udpip_18_Port_1=15352
Udpip_End

Udpip_19_Comment=MINIO기본수신
Udpip_19_Ip_1=233.37.54.246
Udpip_19_Port_1=15361
Udpip_End

Udpip_20_Comment=MINIO시세수신
Udpip_20_Ip_1=233.37.54.246
Udpip_20_Port_1=15365
Udpip_End

#202201 E

# 현물 내부포트 사용
Udpip_21_Comment=유가증권기본수신
Udpip_21_Ip_1=239.255.1.2
Udpip_21_Port_1=18003
Udpip_End

Udpip_22_Comment=유가증권체결(A3)수신1
Udpip_22_Ip_1=239.255.1.2
Udpip_22_Port_1=18001
Udpip_End

Udpip_23_Comment=유가증권체결(A3M4)수신2
Udpip_23_Ip_1=239.255.1.2
Udpip_23_Port_1=18002
Udpip_End

Udpip_24_Comment=유가증권호가(B6B7)수신1
Udpip_24_Ip_1=239.255.1.2
Udpip_24_Port_1=18005
Udpip_End

Udpip_25_Comment=유가증권호가(B6B7)수신2
Udpip_25_Ip_1=239.255.1.2
Udpip_25_Port_1=18006
Udpip_End


Udpip_26_Comment=코스닥기본수신
Udpip_26_Ip_1=239.255.1.2
Udpip_26_Port_1=18012
Udpip_End

Udpip_27_Comment=코스닥체결(A3)수신1
Udpip_27_Ip_1=239.255.1.2
Udpip_27_Port_1=18010
Udpip_End

Udpip_28_Comment=코스닥체결(A3M4)수신2
Udpip_28_Ip_1=239.255.1.2
Udpip_28_Port_1=18011
Udpip_End

Udpip_29_Comment=코스닥호가(B6)수신1
Udpip_29_Ip_1=239.255.1.2
Udpip_29_Port_1=18013
Udpip_End

Udpip_30_Comment=코스닥호가(B6)수신2
Udpip_30_Ip_1=239.255.1.2
Udpip_30_Port_1=18014
Udpip_End


Udpip_31_Comment=ELW체결(A3021)수신1
Udpip_31_Ip_1=239.255.1.2
Udpip_31_Port_1=18015
Udpip_End

Udpip_32_Comment=ELW체결(A3021)수신2
Udpip_32_Ip_1=239.255.1.2
Udpip_32_Port_1=18215
Udpip_End

Udpip_33_Comment=ELW호가(B7021)수신1
Udpip_33_Ip_1=239.255.1.2
Udpip_33_Port_1=18016
Udpip_End

Udpip_34_Comment=ELW호가(B7021)수신2
Udpip_34_Ip_1=239.255.1.2
Udpip_34_Port_1=18216
Udpip_End

# ##################################################### #
# 파생내부포트 (잠시사용)
# ##################################################### #
Udpip_35_Comment=지수선물A0
Udpip_35_Ip_1=239.255.1.2
Udpip_35_Port_1=18020
Udpip_End

Udpip_36_Comment=지수선물B6
Udpip_36_Ip_1=239.255.1.2
Udpip_36_Port_1=18021
Udpip_End

Udpip_37_Comment=지수선물A3G7M4
Udpip_37_Ip_1=239.255.1.2
Udpip_37_Port_1=18022
Udpip_End

Udpip_38_Comment=지수옵션A0
Udpip_38_Ip_1=239.255.1.2
Udpip_38_Port_1=18025
Udpip_End

Udpip_39_Comment=지수옵션CALL
Udpip_39_Ip_1=239.255.1.2
Udpip_39_Port_1=18026
Udpip_End

Udpip_40_Comment=지수옵션PUT
Udpip_40_Ip_1=239.255.1.2
Udpip_40_Port_1=18027
Udpip_End

Udpip_41_Comment=주식선물시세
Udpip_41_Ip_1=239.255.1.2
Udpip_41_Port_1=18038
Udpip_End

Udpip_42_Comment=주식옵션시세
Udpip_42_Ip_1=239.255.1.2
Udpip_42_Port_1=18037
Udpip_End

Udpip_43_Comment=K300시세
Udpip_43_Ip_1=239.255.1.2
Udpip_43_Port_1=18072
Udpip_End

Udpip_44_Comment=K150F시세
Udpip_44_Ip_1=239.255.1.2
Udpip_44_Port_1=18050
Udpip_End

Udpip_45_Comment=K150O시세
Udpip_45_Ip_1=239.255.1.2
Udpip_45_Port_1=18073
Udpip_End

Udpip_46_Comment=미니선물시세
Udpip_46_Ip_1=239.255.1.2
Udpip_46_Port_1=18068
Udpip_End

Udpip_47_Comment=미니옵션시세
Udpip_47_Ip_1=239.255.1.2
Udpip_47_Port_1=18069
Udpip_End

Udpip_48_Comment=지수정보
Udpip_48_Ip_1=239.255.1.2
Udpip_48_Port_1=18018
Udpip_End

# ##################################################### #
# 시세송신 Port
# ##################################################### #
Udpip_49_Comment=지수선물시세송신
Udpip_49_Port_1=60631
Udpip_End

Udpip_50_Comment=지수Call옵션시세송신
Udpip_50_Port_1=60632
Udpip_End

Udpip_51_Comment=지수Put옵션시세송신
Udpip_51_Port_1=60633
Udpip_End

Udpip_52_Comment=손익Ticker송신
Udpip_52_Port_1=60606
Udpip_End

Udpip_53_Comment=손익Ticker송신(ELW)
Udpip_53_Port_1=61616
Udpip_End

# ##################################################### #
# 해외시세송신 Port
# ##################################################### #
Udpip_54_Comment=FCME/FCMX_Master
Udpip_54_Ip_1=239.255.1.11
Udpip_54_Port_1=31501
Udpip_End

Udpip_55_Comment=FCME_시세01
Udpip_55_Ip_1=239.255.1.11
Udpip_55_Port_1=31502
Udpip_End

Udpip_56_Comment=FCME_시세02
Udpip_56_Ip_1=239.255.1.11
Udpip_56_Port_1=31503
Udpip_End

Udpip_57_Comment=FCME_시세03
Udpip_57_Ip_1=239.255.1.11
Udpip_57_Port_1=31504
Udpip_End

Udpip_58_Comment=FCME_시세04
Udpip_58_Ip_1=239.255.1.11
Udpip_58_Port_1=31505
Udpip_End

Udpip_59_Comment=FCME_시세05
Udpip_59_Ip_1=239.255.1.11
Udpip_59_Port_1=31506
Udpip_End

Udpip_60_Comment=FCME_시세06
Udpip_60_Ip_1=239.255.1.11
Udpip_60_Port_1=31507
Udpip_End

Udpip_61_Comment=FCMX_시세
Udpip_61_Ip_1=239.255.1.11
Udpip_61_Port_1=31511
Udpip_End

Udpip_62_Comment=FSGX_Master
Udpip_62_Ip_1=239.255.1.11
Udpip_62_Port_1=31515
Udpip_End

Udpip_63_Comment=FSGX_시세
Udpip_63_Ip_1=239.255.1.11
Udpip_63_Port_1=31516
Udpip_End

Udpip_64_Comment=FEUX_Master
Udpip_64_Ip_1=239.255.1.11
Udpip_64_Port_1=31517
Udpip_End

Udpip_65_Comment=FEUX_시세
Udpip_65_Ip_1=239.255.1.11
Udpip_65_Port_1=31518
Udpip_End

Udpip_66_Comment=FHKG_Master
Udpip_66_Ip_1=239.255.1.11
Udpip_66_Port_1=31519
Udpip_End

Udpip_67_Comment=FHKG_시세
Udpip_67_Ip_1=239.255.1.11
Udpip_67_Port_1=31520
Udpip_End

PA_CONF_END

##########################################################################
# End of File (udpip.ini)
##########################################################################
