##########################################################################
# PROCESS 정보 환경 설정 (proc.ini)
##########################################################################
#   ID: process ID
#   Status: run or stop flag
#   Type: process type
#       MP:Manager Process, DD:Divide Division, TR:TCP Receive, TS:TCP Send,
#       TA:TCP Send/Receive, BR:DB Receive, BS:DB Send
#   IFN_1 ~ IFN_3: input file name 1 ~ 3
#   IDN_1 ~ IDN_3: input data SHM base name 1 ~ 3
#   FFN_1 ~ FFN_3: input FIFO name 1 ~ 3
#   ICN_1 ~ ICN_3: input cisam name 1 ~ 3
#   OFN_1 ~ OFN_9: output file name 1 ~ 9
#   ODN_1 ~ ODN_9: output data SHM base name 1 ~ 9
#   OCN_1 ~ OCN_3: output cisam name 1 ~ 3
#   Start_Time: start time (0000 ~ 2359)
#   End_Time: end time (0000 ~ 2359)
#   Time_Out: timeout (in second)
#   Delay: PS delay check time (in millisecond)
#   Data_Buf: data buffer 사용여부 (Y:사용)
#   Tcp1_Type: TCP/IP (mater daemon 방식) port type (M:master, S:service)
#   Tcp1_Port: TCP/IP (mater daemon 방식) port number
#   Tcp2_Primary: TCP/IP (직접접속 방식) dup ID and port number (primary)
#       e.g. Tcp2_Primary=0,6941 (0:dup ID, 6941:port number)
#   Tcp2_Backup: TCP/IP (직접접속 방식) dup ID and port number (backup)
#   Udp_Port: UDP/IP dup ID and port number
#   Dup_Id: dup ID of TCP2 or UDP port
##########################################################################
#   1:채권
#   2:파생주문처리
#   5:자동전략
#   6:조회처리
#   7:시세
#   8:Client관련
#   9:한도
#   3,4:예비
##########################################################################
PB_CONF_START
Proc_Count=4

Proc_1_Comment=채권KTS_시세수신
Proc_1_ID=pb_7102_ur
Proc_1_Status=R
Proc_1_Type=UR
Proc_1_Udp_Port=0,11402
Proc_1_OFN_1=pb_7102_dd
Proc_1_Start_Time=0500
Proc_1_End_Time=2300
Proc_1_Time_Out=0
Proc_End

Proc_2_Comment=채권kts_M4수신
Proc_2_ID=pb_7103_ur
Proc_2_Status=S
Proc_2_Type=UR
Proc_2_Udp_Port=0,11406
Proc_2_Start_Time=0500
Proc_2_End_Time=2300
Proc_2_Time_Out=0
Proc_End

#################################################################
#관리
#################################################################
Proc_3_Comment=SyncManager
Proc_3_ID=pb_1001_mp
Proc_3_Status=S
Proc_3_Type=MP
#S:0430,E:0400
Proc_3_Start_Time=0500
Proc_3_End_Time=0330
Proc_End

Proc_4_Comment=LogManager
Proc_4_ID=pb_2001_mp
Proc_4_Status=R
Proc_4_Type=MP
Proc_4_Start_Time=0500
Proc_4_End_Time=0330
Proc_End

PB_CONF_END

##########################################################################
# TCPIP업무접속
##########################################################################

##########################################################################
# End of File (proc.ini)
##########################################################################
