##########################################################################
# 접속 허용 client IP address (client 운영) (pc.ini)
##########################################################################
# 172.30.201.26		윤형석
# 172.30.201.48		박상훈
# 172.30.201.74		홍준표
# 172.30.201.76		박세호
# 172.30.201.80		박세호
# 172.30.201.84		티엘정보통신
# 172.30.201.114	최구현
##########################################################################
172.30.201.26
172.30.201.48
172.30.201.74
172.30.201.76
172.30.201.80
172.30.201.84
172.30.201.114

##########################################################################
# End of File (pc.ini)
##########################################################################

