##########################################################################
# UDPIP 정보 환경 설정 (udpip.ini)
##########################################################################
#	Comment: 설명 (max 40 bytes)
#	Ip_1 ~ Ip_20: server ip address
#		All numbers supplied as parts in dot notation can be decimal, octal,
#		or hexadecimal, as specified in the C language (i.e., a leading 0x or
#		0X implies hexadecimal; a leading 0 implies octal; otherwise, the
#		number is interpreted as decimal).
#		e.g. 172.30.220.151 (correct), 172.030.220.151 (false)
#	Dup_Id: avoiding duplication of port
#	Port_1 ~ Port_20: server port number
##########################################################################
# 선물옵션주문체결
##########################################################################
PA_CONF_START
Udpip_Count=12

######################################################################
#  채권100M "운영_10301/TEST_11301/재전송_20301" 
#  - A701K/B601K/A301K/G701K/A601K/I2000
#            운영_11412/TEST_12412/재전송_20401
#  - M4/R3/R4:장운영스케줄공개/회원제재해제공개/일반채권 결제적용 기준환율 공개
#            운영_11406/TEST_12406/재전송_20401
#   <시세>
#	8M   : 233.38.231.152, 10402/11402/12402/20401
#	512K : 233.38.231.162, 10412/11412/12412/20401
#	<장운영>
#	8M   : 233.38.231.153, 10406/11406/12406/20401
#	512K : 233.38.231.153, 10406/11406/12406/20401
#	
######################################################################
Udpip_1_Comment=채권시세수신
Udpip_1_Ip_1=233.38.231.91
Udpip_1_Port_1=10402
Udpip_End

Udpip_2_Comment=채권장운영수신
Udpip_2_Ip_1=233.38.231.153
Udpip_2_Port_1=10406
Udpip_End


######################################################################
#  선물통합100M "운영_10301/TEST_11301/재전송_20301" 
######################################################################
#   10301 Port 수신 TR
#	C406F, M706F, A006F, H606F, H106F, H206F, H306F, H506F, B206F, HA06F 
#   금융상품선물(국채,금리,통화) 수신TR : A006F, I2000
#                          운영/테스트/부산테스트/재수신
#   <A0>
#   100M  : 233.38.231.91,  10301/11301/12301/20301
#    12M  : 233.38.231.91,  10301/11301/12301/20301
######################################################################
#	- 파생 협의거래 결과 
#	C401F, C402F, C404F, C406F, C408F, C409F, C410F, C411F, C413F
#	- Eurex연계 장개시전 협의거래
#	M701F, M706F, M711F
#	- 파생 종목정보_수신
#	A001F, A002F, A004F, A006F, A008F, A009F, A010F, A011F, A013F
#	- 금융상품선물 결제기준 국고채권 정보
#	H606F
#	- 파생 상품별 투자자별 통계
#	H101F, H102F, H104F, H106F, H108F, H109F, H110F, H111F, H113F
#	- 파생종목 미결제약정수량 데이터
#	H201F, H202F, H204F, H206F, H208F, H209F, H210F, H211F, H213F
#	선물종목 정산가격 데이터
#	H301F, H302F, H304F, H306F, H308F, H309F, H310F, H311F, H313F
#	- 금융상품선물 현물정보 결제기준 국고채권 수익률 및 CD금리
#	H506F, H599F
#	파생 시세 Snapshot (우선호가 5단계)
#	B201F, B202F, B204F, B206F, B208F, B209F, B210F, B211F, B213F
#	- 파생 시세 Snapshot (우선호가 10단계) - 주식선물만
#	B204F
#	- RFR일별공시금리 - 3개월무위험지표금리선물 상장 반영
#	HA06F
#	- 주식파생 조정내역
#	H404F
#	- Polling_수신	
#	I2000
######################################################################

Udpip_3_Comment=금융상품선물A0수신
Udpip_3_Ip_1=233.38.231.91
Udpip_3_Port_1=10301
Udpip_End

Udpip_4_Comment=금융상품선물A0수신_재전송
Udpip_4_Ip_1=233.38.231.91
Udpip_4_Port_1=20301
Udpip_End

######################################################################
#	- 10302(코스피200선물)
#	- 10303(코스닥150선물)
#	- 10304(개별주식선물)
#	- 10305(금융상품선물(국채,금리,통화))
#	- 10306(일반상품선물(금, 돈육(휴면)))
#	- 10307(미니코스피200선물)
#	- 10308(코스피200변동성지수선물)
#	- 10309(코스피200섹터지수선물
#	- 10310(KRX300선물)
######################################################################
#	해당 Port(10305) 사용 TR
#    A306F : 파생체결
#    G706F : 파생체결G7 (우선호가  5단계) 04F & 05F(제외)
#    B606F : 파생우선호가 (우선호가  5단계) 04F & 05F(제외)
#    R106F : 파생 장운영TS + 우선호가 (우선호가  5단계) 단일가 세션, 04F, 05F 제외
#
#    A706A : 장운영정보(모든 A7공통.. All)
#    M406A : 장운영스캐쥴
#
#    A601F : 파생종목마감
#    Q201F : 파생동적상하한가 적용및해제(05없음)
#    V101F : 가격제한폭확대발동
#    I2000 : Polling Data
######################################################################
#	- 장운영TS
#	A701F, A702F, A704F, A706F, A708F, A709F, A710F, A711F, A713F
#	- 배분정보
#	O601F, O602F, O604F, O606F, O608F, O609F, O610F, O611F, O613F
#	- 파생 우선호가 (우선호가 5단계)
#	B601F, B602F, B604F, B606F, B608F, B609F, B610F, B611F, B613F
#	- 파생 우선호가 (우선호가 10단계) - 주식선물만
#	B604F
#	- 파생 체결
#	A301F, A302F, A304F, A306F, A308F, A309F, A310F, A311F, A313F
#	- 파생 체결 + 우선호가 (우선호가 5단계)
#	G701F, G702F, G704F, G706F, G708F, G709F, G710F, G711F, G713F
#	- 파생 체결 + 우선호가 (우선호가 10단계) - 주식선물만
#	G704F
#	- 파생 장운영TS + 우선호가 (우선호가 5단계)
#	R101F, R102F, R104F, R106F, R108F, R109F, R110F, R111F, R113F
#	- 파생 장운영TS + 우선호가 (우선호가 10단계) - 주식선물만
#	R104F
#	- 파생 종목마감
#	A601F, A602F, A604F, A606F, A608F, A609F, A610F, A611F, A613F
#	- 파생 동적상하한가 적용 및 해제
#	Q201F, Q202F, Q204F, Q206F, Q208F, Q209F, Q210F, Q211F
#	- 파생 가격제한폭확대발동
#	V101F, V102F, V104F, V108F, V109F, V111F, V113F
#	- Polling
#	I2000
######################################################################
#	10305(금융상품선물(국채,금리,통화)) 만 사용
#  선물통합100M "운영_10305/TEST_11305/재전송_20301" 
#	<A3/G7/B6/시세>
#	100M  : 233.38.231.92,  10305/11305/12305/20305
#	 12M  : 233.38.231.112, 10345/11345/12345/20345
#	<M4>
#	100M  : 233.38.231.93,  10315/11315/12315/20301
#	 12M  : 233.38.231.93,  10315/11315/12315/20301
######################################################################
Udpip_5_Comment=금융상품선물시세수신_G7등
Udpip_5_Ip_1=233.38.231.92
Udpip_5_Port_1=10305
Udpip_End

Udpip_6_Comment=금융상품M4수신
Udpip_6_Ip_1=233.38.231.93
Udpip_6_Port_1=10315
Udpip_End

# ##################################################### #
# 시세송신 Port
# ##################################################### #
Udpip_7_Comment=채권시세송신
Udpip_7_Port_1=60612
Udpip_End

Udpip_8_Comment=채권M4송신
Udpip_8_Port_1=60613
Udpip_End

Udpip_9_Comment=금융상품선물A0송신
Udpip_9_Port_1=60621
Udpip_End

Udpip_10_Comment=금융상품선물시세송신
Udpip_10_Port_1=60622
Udpip_End

Udpip_11_Comment=금융상품선물시세송신
Udpip_11_Port_1=60623
Udpip_End

# ##################################################### #
# Add Hong
# ##################################################### #
Udpip_12_Comment=금융상품시세수신_호가
Udpip_12_Ip_1=227.10.20.30
Udpip_12_Port_1=30021
Udpip_End

PA_CONF_END

##########################################################################
# End of File (udpip.ini)
##########################################################################
