## 공백이 있으면 안됨.

## 전략설정 / 종료 송수신
[OMS]
log_level=3
log_file=/fslog/win
cli_port=4000
cmd_port=32011
rpl_port=32001
msg_key=

## 채권 Drop Copy 수신 ( OMS 송신Data 수신)
[RDS_DC]
log_level=3
log_file=/fslog/kei/win
cli_port=4001
port=32009
file_name=/fsfxwin/fep/agt/data
msg_key=0xff170610

##공개 장운영 수신
[RDS_IS]
log_level=3
log_file=/fslog/kei/win
cli_port=4002
port=32008
file_name=/fsfxwin/fep/agt/data
msg_key=0xff170620

## 채권종목정보 수신
[RDS_R1]
log_level=3
log_file=/fslog/kei/win
cli_port=4004
port=32017
file_name=/fsfile/filedata/fxwin/recv/KEI_BW540003_TRDESP50101.txt
msg_key=

## KTS종목정보 수신
[RDS_R2]
log_level=3
log_file=/fslog/kei/win
cli_port=4005
port=32018
file_name=/fsfile/filedata/fxwin/recv/KEI_BW540003_TRDESP50102.txt
msg_key=

## 일괄 송수신(지점)
[BATCH]
log_level=3
log_file=/fslog/kei/win
cli_port=4003
cmd_port=32019
rpl_port=32016
file_name=/fsfxwin/fep/agt/data
msg_key=
