/** ***************************************************************************
**  @file       main.h
**  @date       2024/01/25
**  @author     ibk
**  @version    
**  @brif
**  asis otp_agent.h와 iniparser.h를 통합 하나의 header로
***************************************************************************** */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>
#include <dirent.h>
#include <sys/stat.h>
#include <unistd.h>
#include <fcntl.h>
#include <signal.h>

/*******************************************************************************/
/*******************************************************************************/
/*******************************************************************************/
/*******************************************************************************/
/*******************************************************************************/
/*******************************************************************************/
/*
 Based upon libiniparser, by Nicolas Devillard
 Hacked into 1 file (m-iniparser) by Freek/2005
 Original terms following:

 -- -

 Copyright (c) 2000 by Nicolas Devillard (ndevilla AT free DOT fr).

 Written by Nicolas Devillard. Not derived from licensed software.

 Permission is granted to anyone to use this software for any
 purpose on any computer system, and to redistribute it freely,
 subject to the following restrictions:

 1. The author is not responsible for the consequences of use of
 this software, no matter how awful, even if they arise
 from defects in it.

 2. The origin of this software must not be misrepresented, either
 by explicit claim or by omission.

 3. Altered versions must be plainly marked as such, and must not
 be misrepresented as being the original software.

 4. This notice may not be removed or altered.

 */


#ifndef _INIPARSER_H_
#define _INIPARSER_H_
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <ctype.h>


typedef struct _dictionary_ {
        /** Number of entries in dictionary */
        int n;
        /** Storage size */
        int size;
        /** List of string values */
        char **val;
        /** List of string keys */
        char **key ;
        /** List of hash values for keys */
        unsigned *hash;
} dictionary ;


/* generated by genproto */

dictionary * iniparser_new(char *ininame);
void iniparser_free(dictionary * d);

int iniparser_getnsec(dictionary * d);
char * iniparser_getsecname(dictionary * d, int n);
void iniparser_dump(dictionary * d, FILE * f);
void iniparser_dump_ini(dictionary * d, FILE * f);
char * iniparser_getkey(dictionary *d, char *section, char *key);
char * iniparser_getstr(dictionary * d, char * key);
char * iniparser_getstring(dictionary * d, char * key, char * def);
int iniparser_getint(dictionary * d, char * key, int notfound);
double iniparser_getdouble(dictionary * d, char * key, double notfound);
int iniparser_getboolean(dictionary * d, char * key, int notfound);
int iniparser_find_entry(dictionary  *   ini, char        *   entry);
int iniparser_setstr(dictionary * ini, char * entry, char * val);
void iniparser_unset(dictionary * ini, char * entry);



#endif

/*******************************************************************************/
/*******************************************************************************/
/*******************************************************************************/
/*******************************************************************************/
/*******************************************************************************/
#ifndef _OTP_AGENT_H_
#define _OTP_AGENT_H_

#ifdef __cplusplus
extern "C" {
#endif

/* otp_agent.h */
/********************************************************/
/* Copyright 2007 Cyclops Inc.                    */
/********************************************************/


/* 자행,타행 구분 값 */
#define IBK_ORG_CODE                    "1"
#define OTHER_ORG_CODE                  "2"


/********************************************************/
/* 각 필드 길이             */
/********************************************************/
#define LEN_RES_CODE            6
#define LEN_ERR_COUNT           2
#define LEN_BIZ_CODE            6
#define LEN_OTHER_ORG           1

#define LEN_VENDER_CODE 3
#define LEN_USER_CODE           13
#define LEN_TOKEN_SERIAL        12
#define LEN_TOKEN_CODE          8

#define LEN_AUTH_DATE           8
#define LEN_AUTH_TIME           6

/********************************************************/
/* 입력 Structure            */
/********************************************************/
typedef struct OTP_DATA  {
        char resCode[LEN_RES_CODE+2];
        char otherOrg[LEN_OTHER_ORG+2];                 /* 타행 2, 당행 1 */
        char venderCode[LEN_VENDER_CODE+2];             /* HOST 조회 시 가져옴 */
        char userCode[LEN_USER_CODE+2];                 /* 실명번호(텔레뱅킹), 이용자번호(인터넷뱅킹) */
        char tokSerial[LEN_TOKEN_SERIAL+2];             /* HOST 조회 시 가져옴 */
        char tokCode[LEN_TOKEN_CODE+2];                 /* OTP 응답값 -> 이용자 입력 */
        char lastAuthDate[LEN_AUTH_DATE+2];             /* 마지막 인증 성공일자 */
        char lastAuthTime[LEN_AUTH_TIME+2];             /* 마지막 인증 성공시간 */
        char errCount[LEN_ERR_COUNT+2];
}stOtpData;

/*===========================================================================
FUNCTION                : Af_AuthOtpUser
PARAMETERS              : in 입력 구조체
                              out 결과 구조체
DESCRIPTION             : OTP 인증 요구
DEPENDENCIES    : None
RETURNS                 : return code
SIDE EFFECTS    : None
===========================================================================*/
 extern void Af_AuthOtpUser(stOtpData *in, stOtpData *out);

/*===========================================================================
FUNCTION                : Af_ResyncOtpUser
PARAMETERS              : in 입력 구조체
                                  out 결과 구조체
DESCRIPTION             : OTP 보정 요구
DEPENDENCIES    : None
RETURNS                 : return code 
SIDE EFFECTS    : None
===========================================================================*/
extern void Af_ResyncOtpUser(stOtpData *in, stOtpData *out );

#ifdef __cplusplus
}
#endif

#endif


