/*------------------------------------------------------------------------
#   Module  : SQLite DB to .ini export tool
#   File    : db2ini.c
#   Description : Exports FEP config from fep_config.db to .ini files.
#                 Reverse operation of ini2db.
#                 Produces .ini files readable by existing FEP parsers.
#
#   Usage   : db2ini -e ENV_ID [-s SYS] [-d DB_PATH] [-o OUT_DIR]
#
#   Build   : cc -o db2ini db2ini.c -lsqlite3
------------------------------------------------------------------------*/

#include    <stdio.h>
#include    <stdlib.h>
#include    <string.h>
#include    <ctype.h>
#include    <sys/stat.h>
#include    <sqlite3.h>

/*------------------------------------------------------------------------
    Constants
------------------------------------------------------------------------*/
#define     MAX_KEY     100
#define     MAX_VAL     512

/*------------------------------------------------------------------------
    Group definitions (same as ini2db)
------------------------------------------------------------------------*/
typedef struct {
    const char  *group_id;
    const char  *ini_file;
    const char  *end_marker;
    int         is_daemon;
} GROUP_DEF;

static GROUP_DEF g_groups[] = {
    { "daemon",  "daemon.ini",  "Daemon_End",  1 },
    { "file",    "file.ini",    "File_End",    0 },
    { "dshm",    "dshm.ini",    "Dshm_End",    0 },
    { "tcp1",    "tcp1.ini",    "Tcp1_End",    0 },
    { "tcp2",    "tcp2.ini",    "Tcp2_End",    0 },
    { "udpip",   "udpip.ini",   "Udpip_End",   0 },
    { "sisetr",  "sisetr.ini",  "Sise_End",    0 },
    { "proc",    "proc.ini",    "Proc_End",    0 },
    { NULL, NULL, NULL, 0 }
};

/*------------------------------------------------------------------------
    Global state
------------------------------------------------------------------------*/
static sqlite3      *g_db = NULL;
static int          g_total_keys = 0;
static int          g_total_files = 0;

/*------------------------------------------------------------------------
    Export daemon.ini from DB
    DB format: section='A', key_name='ID', key_value='01'
    INI format: DAEMON_A_ID=01
------------------------------------------------------------------------*/
static int export_daemon_ini(const char *env_id, const char *out_path) {
    sqlite3_stmt    *stmt = NULL;
    FILE            *fp;
    int             rc, count = 0;
    char            prev_section[4];
    int             first_section = 1;
    static const char *sql =
    "SELECT section, key_name, key_value "
    "FROM fep_config "
    "WHERE env_id=? AND group_id='daemon' "
    "ORDER BY section, sort_order";

    rc = sqlite3_prepare_v2(g_db, sql, -1, &stmt, NULL);
    if (rc != SQLITE_OK) {
        fprintf(stderr, "ERROR: prepare failed: %s\n",
                sqlite3_errmsg(g_db));
        return -1;
    }

    sqlite3_bind_text(stmt, 1, env_id, -1, SQLITE_STATIC);

    fp = fopen(out_path, "w");
    if (fp == NULL) {
        fprintf(stderr, "ERROR: cannot create %s\n", out_path);
        sqlite3_finalize(stmt);
        return -1;
    }

    fprintf(fp, "# Generated by db2ini(env=%s)\n", env_id);
    fprintf(fp, "DAEMON_CONF_START\n");

    memset(prev_section, 0, sizeof (prev_section));

    while (sqlite3_step(stmt) == SQLITE_ROW) {
        const char  *section  = (const char *) sqlite3_column_text(stmt, 0);
        const char  *key_name = (const char *) sqlite3_column_text(stmt, 1);
        const char  *key_val  = (const char *) sqlite3_column_text(stmt, 2);

        if (section == NULL || key_name == NULL)
            continue;

        /* new section -> close previous with end marker */
        if (strcmp(prev_section, section) != 0) {
            if (!first_section)
                fprintf(fp, "Daemon_End\n");

            strncpy(prev_section, section, sizeof (prev_section) - 1);
            first_section = 0;
        }

        /* write DAEMON_{section}_{key_name}={value} */
        fprintf(fp, "DAEMON_%s_%s=%s\n",
                section, key_name,
                key_val != NULL ? key_val : "");

        count++;
    }

    /* close last section */
    if (!first_section)
        fprintf(fp, "Daemon_End\n");

    fprintf(fp, "DAEMON_CONF_END\n");

    fclose(fp);
    sqlite3_finalize(stmt);

    g_total_keys += count;
    g_total_files++;
    printf("  daemon.ini : %d keys\n", count);
    return count;
}

/*------------------------------------------------------------------------
    Export generic .ini from DB (tcp2, tcp1, udpip, proc, file, dshm, sisetr)
    DB format: section='A', key_name='TCP2_PORT', key_value='12345'
    INI format:
        PA_CONF_START
        TCP2_PORT=12345
        TCP2_IP=10.1.1.1
        Tcp2_End
        PA_CONF_END
------------------------------------------------------------------------*/
static int export_generic_ini(const char *env_id, const char *group_id,
        const char *sys_prefix, const char *end_marker, const char *out_path) {
    sqlite3_stmt    *stmt = NULL;
    FILE            *fp;
    int             rc, count = 0;
    char            prev_section[4];
    char            first_key_in_item[MAX_KEY];
    int             first_in_section = 1;
    int             item_started = 0;
    static const char *sql =
    "SELECT section, key_name, key_value "
    "FROM fep_config "
    "WHERE env_id=? AND group_id=? "
    "ORDER BY section, sort_order";

    rc = sqlite3_prepare_v2(g_db, sql, -1, &stmt, NULL);
    if (rc != SQLITE_OK) {
        fprintf(stderr, "ERROR: prepare failed: %s\n",
                sqlite3_errmsg(g_db));
        return -1;
    }

    sqlite3_bind_text(stmt, 1, env_id, -1, SQLITE_STATIC);
    sqlite3_bind_text(stmt, 2, group_id, -1, SQLITE_STATIC);

    fp = fopen(out_path, "w");
    if (fp == NULL) {
        fprintf(stderr, "ERROR: cannot create %s\n", out_path);
        sqlite3_finalize(stmt);
        return -1;
    }

    fprintf(fp, "# Generated by db2ini(env=%s)\n", env_id);

    memset(prev_section, 0, sizeof (prev_section));
    memset(first_key_in_item, 0, sizeof (first_key_in_item));

    while (sqlite3_step(stmt) == SQLITE_ROW) {
        const char  *section  = (const char *) sqlite3_column_text(stmt, 0);
        const char  *key_name = (const char *) sqlite3_column_text(stmt, 1);
        const char  *key_val  = (const char *) sqlite3_column_text(stmt, 2);

        if (section == NULL || key_name == NULL)
            continue;

        /* new section -> close previous, open new */
        if (strcmp(prev_section, section) != 0) {
            /* close previous section */
            if (!first_in_section) {
                if (item_started)
                    fprintf(fp, "%s\n", end_marker);
                fprintf(fp, "%c%s_CONF_END\n",
                        sys_prefix[0], prev_section);
            }

            /* open new section */
            fprintf(fp, "%c%s_CONF_START\n",
                    sys_prefix[0], section);

            strncpy(prev_section, section, sizeof (prev_section) - 1);
            first_in_section = 0;
            item_started = 0;
            memset(first_key_in_item, 0, sizeof (first_key_in_item));
        }

        /* detect item boundary: when key_name matches the first key,
           it means a new logical item starts */
        if (first_key_in_item[0] == '\0') {
            /* remember the first key name of the first item */
            strncpy(first_key_in_item, key_name,
                    sizeof (first_key_in_item) - 1);
            item_started = 1;
        }
        else if (strcmp(key_name, first_key_in_item) == 0) {
            /* new item starts - emit end marker for previous item */
            fprintf(fp, "%s\n", end_marker);
        }

        /* write key=value */
        fprintf(fp, "%s=%s\n", key_name,
                key_val != NULL ? key_val : "");

        count++;
    }

    /* close last section */
    if (!first_in_section) {
        if (item_started)
            fprintf(fp, "%s\n", end_marker);
        fprintf(fp, "%c%s_CONF_END\n",
                sys_prefix[0], prev_section);
    }

    fclose(fp);
    sqlite3_finalize(stmt);

    g_total_keys += count;
    g_total_files++;
    printf("  %-12s: %d keys\n", group_id, count);
    return count;
}

/*------------------------------------------------------------------------
    Export IP whitelist file from DB
------------------------------------------------------------------------*/
static int export_ip_file(const char *env_id, const char *ip_type,
        const char *out_path) {
    sqlite3_stmt    *stmt = NULL;
    FILE            *fp;
    int             rc, count = 0;
    static const char *sql =
    "SELECT ip_address FROM fep_ip_whitelist "
    "WHERE env_id=? AND ip_type=? AND is_active=1 "
    "ORDER BY ip_id";

    rc = sqlite3_prepare_v2(g_db, sql, -1, &stmt, NULL);
    if (rc != SQLITE_OK)
        return -1;

    sqlite3_bind_text(stmt, 1, env_id, -1, SQLITE_STATIC);
    sqlite3_bind_text(stmt, 2, ip_type, -1, SQLITE_STATIC);

    fp = fopen(out_path, "w");
    if (fp == NULL) {
        fprintf(stderr, "ERROR: cannot create %s\n", out_path);
        sqlite3_finalize(stmt);
        return -1;
    }

    fprintf(fp, "# Generated by db2ini(env=%s, type=%s)\n",
            env_id, ip_type);

    while (sqlite3_step(stmt) == SQLITE_ROW) {
        const char  *ip = (const char *) sqlite3_column_text(stmt, 0);

        if (ip != NULL) {
            fprintf(fp, "%s\n", ip);
            count++;
        }
    }

    fclose(fp);
    sqlite3_finalize(stmt);

    if (count > 0) {
        g_total_files++;
        printf("  %-12s: %d IPs\n", ip_type, count);
    }

    return count;
}

/*------------------------------------------------------------------------
    Print usage
------------------------------------------------------------------------*/
static void usage(const char *prog) {
    fprintf(stderr,
            "Usage: %s -e ENV_ID [-s SYS] [-d DB_PATH] [-o OUT_DIR]\n"
            "\n"
            "  -e ENV_ID    Environment ID(TEST, REAL1, REAL2)\n"
            "  -s SYS       System prefix character(default: P)\n"
            "  -d DB_PATH   SQLite DB path(default: $_FEP_CFG/fep_config.db)\n"
            "  -o OUT_DIR   Output directory(default: current directory)\n"
            "\n"
            "Examples:\n"
            "  %s -e TEST\n"
            "  %s -e REAL1 -d /home/fep/st01/cfg/fep_config.db\n"
            "  %s -e TEST -o /tmp/cfg_export\n"
            "  %s -e TEST -s P -o ./cfg\n",
            prog, prog, prog, prog, prog);
}

/*------------------------------------------------------------------------
    Main
------------------------------------------------------------------------*/
int     main(int argc, char *argv[]) {
    char    env_id[20];
    char    sys_prefix[4];
    char    db_path[256];
    char    out_dir[256];
    char    out_path[512];
    char    *env_val;
    int     i, rc;
    int     has_env = 0, has_db = 0, has_out = 0;
    struct stat st;

    memset(env_id, 0, sizeof (env_id));
    memset(db_path, 0, sizeof (db_path));
    memset(out_dir, 0, sizeof (out_dir));
    strcpy(sys_prefix, "P");

    /*-- parse arguments --*/
    for (i = 1; i < argc; i++) {
        if (strcmp(argv[i], "-e") == 0 && i + 1 < argc) {
            strncpy(env_id, argv[++i], sizeof (env_id) - 1);
            /* uppercase env_id */
            {
                char *p = env_id;
                while (*p) {
                    *p = toupper ((unsigned char) *p);
                    p++;
                }
            }
            has_env = 1;
        }
        else if (strcmp(argv[i], "-s") == 0 && i + 1 < argc) {
            sys_prefix[0] = toupper((unsigned char) argv[++i][0]);
            sys_prefix[1] = '\0';
        }
        else if (strcmp(argv[i], "-d") == 0 && i + 1 < argc) {
            strncpy(db_path, argv[++i], sizeof (db_path) - 1);
            has_db = 1;
        }
        else if (strcmp(argv[i], "-o") == 0 && i + 1 < argc) {
            strncpy(out_dir, argv[++i], sizeof (out_dir) - 1);
            has_out = 1;
        }
        else {
            usage(argv[0]);
            return 1;
        }
    }

    if (!has_env) {
        fprintf(stderr, "ERROR: -e ENV_ID is required\n\n");
        usage(argv[0]);
        return 1;
    }

    /*-- determine DB path --*/
    if (!has_db) {
        env_val = getenv("_FEP_CFG");
        if (env_val != NULL)
            snprintf(db_path, sizeof (db_path),
                    "%s/fep_config.db", env_val);
        else
            snprintf(db_path, sizeof (db_path),
                    "./fep_config.db");
    }

    /*-- determine output directory --*/
    if (!has_out)
        strcpy(out_dir, ".");

    /* create output directory if needed */
    if (stat(out_dir, &st) == -1) {
        mkdir(out_dir, 0755);
    }

    printf("================================================\n");
    printf("  db2ini - FEP Config Export Tool\n");
    printf("================================================\n");
    printf("  Environment : %s\n", env_id);
    printf("  System      : %s\n", sys_prefix);
    printf("  DB Path     : %s\n", db_path);
    printf("  Output Dir  : %s\n", out_dir);
    printf("================================================\n\n");

    /*-- open DB (read-only) --*/
    rc = sqlite3_open_v2(db_path, &g_db,
            SQLITE_OPEN_READONLY, NULL);

    if (rc != SQLITE_OK) {
        fprintf(stderr, "ERROR: cannot open DB [%s]: %s\n",
                db_path, sqlite3_errmsg(g_db));
        return 1;
    }

    /*-- export each config group --*/
    for (i = 0; g_groups[i].group_id != NULL; i++) {
        snprintf(out_path, sizeof (out_path),
                "%s/%s", out_dir, g_groups[i].ini_file);

        if (g_groups[i].is_daemon)
            export_daemon_ini(env_id, out_path);
        else
            export_generic_ini(env_id, g_groups[i].group_id,
                    sys_prefix, g_groups[i].end_marker, out_path);
    }

    /*-- export IP whitelist files --*/
    snprintf(out_path, sizeof (out_path), "%s/client.ini", out_dir);
    export_ip_file(env_id, "CLIENT", out_path);

    snprintf(out_path, sizeof (out_path), "%s/pc.ini", out_dir);
    export_ip_file(env_id, "ADMIN", out_path);

    /*-- close DB --*/
    sqlite3_close(g_db);

    /*-- summary --*/
    printf("\n================================================\n");
    printf("  Export Complete\n");
    printf("================================================\n");
    printf("  Config keys : %d\n", g_total_keys);
    printf("  Files       : %d\n", g_total_files);
    printf("================================================\n");

    return 0;
}

/*************************************************************************
    End of Program (db2ini.c)
*************************************************************************/
