#ifndef _KRX_TRDESP50101_H
#define _KRX_TRDESP50101_H

/* TRDESP50101 채권종목정보 - KRX EXTURE 3.0 v3.24 전문 (자동생성, DATA부) */
/* DATA 길이 합계 = 1173 (interface-list.csv '길이(헤더제외)'와 대조) */
typedef struct {
    char Msg_Seq[11];                           /*    1 메세지일련번호 (long 11) */
    char Tr_Cd[11];                             /*    2 트랜잭션코드 (String 11) */
    char Trnsm_Dd[8];                           /*    3 전송일자 (String 8) */
    char Bz_Dd[8];                              /*    4 영업일자 (String 8) */
    char Market_Identification[3];              /*    5 시장ID (String 3) */
    char Isu_Cd[12];                            /*    6 종목코드 (string 12) */
    char Isu_Nm[80];                            /*    7 종목명 (string 80) */
    char Isu_Abbrv[40];                         /*    8 종목약명 (string 40) */
    char Isu_Eng_Nm[80];                        /*    9 종목영문명 (string 80) */
    char Isu_Eng_Abbrv[40];                     /*   10 종목영문약명 (string 40) */
    char Me_Grp_No[2];                          /*   11 ME그룹번호 ★신규 (string 2) */
    char Isur_Cd[5];                            /*   12 발행기관코드 (string 5) */
    char Bnd_List_Tp_Cd[1];                     /*   13 채권상장구분코드 (string 1) */
    char Bnd_Clss_Cd[6];                        /*   14 채권분류코드 (string 6) */
    char Bnd_Tp_Cd[2];                          /*   15 채권유형코드 (string 2) */
    char Munibnd_Tp_Cd[1];                      /*   16 지방채구분코드 (string 1) */
    char Bnd_Guar_Tp_Cd[1];                     /*   17 채권보증구분코드 (string 1) */
    char Grt_Rt[13];                            /*   18 지급보증율 (float 13) */
    char Nusual_Bnd_Tp_Cd[1];                   /*   19 특이채권유형코드 (String 1) */
    char Imbdopt_Corpbnd_Cd[1];                 /*   20 옵션부사채코드 (string 1) */
    char Int_Pay_Methd_Cd[2];                   /*   21 이자지급방법코드 (string 2) */
    char Risk_Bnd_Redmpt_Tp_Cd[1];              /*   22 리스크채권상환유형코드 (sting 1) */
    char Bnd_Isu_Methd_Cd[3];                   /*   23 채권발행방법코드 (string 3) */
    char Asst_Secutiz_Tp_Cd[2];                 /*   24 자산유동화구분코드 (string 2) */
    char Debt_Repay_Rank_Tp_Cd[1];              /*   25 채무변제순위구분코드 (string 1) */
    char List_Dd[8];                            /*   26 상장일자 (string 8) */
    char Isu_Dd[8];                             /*   27 발행일자 (string 8) */
    char Redmpt_Dd[8];                          /*   28 상환일자 (string 8) */
    char Sale_Dd[8];                            /*   29 매출일 (string 8) */
    char Fst_Int_Pay_Dd[8];                     /*   30 최초이자지급일자 (string 8) */
    char Bnd_Isu_Rt[13];                        /*   31 채권발행율 (float 13) */
    char Coupn_Rt[14];                          /*   32 표면이자율 (float 14) */
    char Int_Pay_Calc_Mms[4];                   /*   33 이자지급계산월수 (long 4) */
    char Coupn_Pay_Methd_Cd[1];                 /*   34 이표지급방법코드 (string 1) */
    char Int_Dd_Pay_Bas_Tp_Cd[1];               /*   35 이자일지급기준구분코드 (string 1) */
    char Int_Mmend_Tp_Cd[1];                    /*   36 이자월말구분코드 (string 1) */
    char Int_Unwon_Ud_Procs_Cd[1];              /*   37 이자원단위미만처리코드 (string 1) */
    char Int_Pay_Unit_Mms[4];                   /*   38 이자지급단위월수 (string 4) */
    char Bnd_Sale_Tp_Cd[1];                     /*   39 채권매출형태코드 (string 1) */
    char Bnd_Pre_Sale_Int_Pay_Methd_Cd[1];      /*   40 채권선매출이자지급방법코드 (string 1) */
    char Isu_Amt[22];                           /*   41 발행금액 (float 22) */
    char List_Amt[22];                          /*   42 상장금액 (float 22) */
    char Pack_Amt_Final_Yn[1];                  /*   43 일괄금액확정여부 (string 1) */
    char Curr_Tp_Cd[1];                         /*   44 통화구분코드 (string 1) */
    char Exp_Redmpt_Rto[13];                    /*   45 만기상환비율 (float 13) */
    char Grt_Yd[13];                            /*   46 보장수익률 (float 13) */
    char Grt_Yd_Strt_Dd[8];                     /*   47 보장수익률적용일자 (string 8) */
    char Add_Yd[13];                            /*   48 추가수익률 (float 13) */
    char Add_Yd_Strt_Dd[8];                     /*   49 추가수익률적용일자 (string 8) */
    char Eqmt_Fnd[22];                          /*   50 시설자금 (float 22) */
    char Oper_Fnd[22];                          /*   51 운영자금 (float 22) */
    char Refund_Fnd[22];                        /*   52 차환자금 (float 22) */
    char Misc_Fnd[22];                          /*   53 기타자금 (float 22) */
    char Sign_Yn[1];                            /*   54 기명여부 (string 1) */
    char Tax_Yn[1];                             /*   55 과세여부 (string 1) */
    char Majagnt_Inst_Cd[4];                    /*   56 주관기관코드 (string 4) */
    char Grt_Inst_Cd[4];                        /*   57 지급보증기관코드 (string 4) */
    char Trst_Inst_Cd[4];                       /*   58 수탁기관코드 (string 4) */
    char Reg_Inst_Cd[4];                        /*   59 등록기관코드 (string 4) */
    char Princint_Pay_Agnt_Cd[4];               /*   60 원리금지급대행기관코드 (string 4) */
    char Bnd_Srt_Cd[9];                         /*   61 채권단축코드 (string 9) */
    char Bnd_Delist_Rsn_Cd[2];                  /*   62 채권상장폐지사유코드 (string 2) */
    char Bnd_Delist_Dd[8];                      /*   63 채권상장폐지일자 (string 8) */
    char Stk_Rel_Corpbnd_Rght_Tp_Cd[2];         /*   64 주식관련사채권리구분코드 (string 2) */
    char Obj_Isu_Cd[12];                        /*   65 대상종목코드 (string 12) */
    char Obj_Isu_Nm[60];                        /*   66 대상종목명 (string 60) */
    char Stk_Rel_Corpbnd_Exer_Prc[11];          /*   67 주식관련사채권리행사가격 (float 11) */
    char Exer_Rto[7];                           /*   68 행사비율 (float 7) */
    char Exer_Strt_Dd[8];                       /*   69 행사개시일자 (string 8) */
    char Exer_End_Dd[8];                        /*   70 행사종료일자 (string 8) */
    char Cash_Pay_Rto[4];                       /*   71 현금납입비율 (long 4) */
    char Sb_Pay_Rto[4];                         /*   72 대용납입비율 (long 4) */
    char Clm_Inst_Cd[4];                        /*   73 청구기관코드 (string 4) */
    char Div_Reck_Dd_Tp_Cd[1];                  /*   74 배당기산일구분코드 (string 1) */
    char Proft_Partc_Acc_Yn[1];                 /*   75 이익참가누적여부 (string 1) */
    char Subsrght_Exer_Af_Isu_Cd[12];           /*   76 신주인수권행사이후종목코드 (string 12) */
    char Split_Redmpt_Tp_Cd[1];                 /*   77 분할상환유형구분코드 (string 1) */
    char Equiv_Redmpt_Val[22];                  /*   78 균등상환액 (float 22) */
    char Defr_Mms[4];                           /*   79 거치개월수 (long 4) */
    char Redmpt_Pd_Int_Tp_Cd[1];                /*   80 상환기간이자구분코드 (string 1) */
    char Split_Redmpt_Cnt[5];                   /*   81 분할상환횟수 (long 5) */
    char Int_Rt_Decsn_Misc_Bas_Int_Nm[20];      /*   82 이자율결정기타기준금리명 (string 20) */
    char Spd[10];                               /*   83 가산금리 (float 10) */
    char Uplmt_Coupn_Rt[14];                    /*   84 상한표면이자율 (float 14) */
    char Lowlmt_Coupn_Rt[14];                   /*   85 하한표면이자율 (float 14) */
    char Halt_Yn[1];                            /*   86 거래정지여부 (string 1) */
    char Halt_Rsn_Cd[3];                        /*   87 거래정지사유코드 (string 3) */
    char Small_Trd_Kind_Cd[3];                  /*   88 소액매매종류코드 (string 3) */
    char Prevpd_Int_Pay_Dd[8];                  /*   89 전기이자지급일자 (string 8) */
    char Nxtpd_Int_Pay_Dd[8];                   /*   90 차기이자지급일자 (string 8) */
    char Sb_Prc[11];                            /*   91 대용가격 (float 11) */
    char Exchrt_Appl_Sb_Prc[11];                /*   92 환율적용대용가격 (float 11) */
    char Bnd_Clsprc[11];                        /*   93 채권종가 (float 11) */
    char Clsprc_Yd[13];                         /*   94 종가수익률 (float 13) */
    char Clsprc_Form_Dd[8];                     /*   95 종가형성일자 (string 8) */
    char If_Trdvol[16];                         /*   96 I/F거래량 (long 16) */
    char Bas_Prc[11];                           /*   97 기준가격 (float 11) */
    char Nusual_Isu_Cond_Contn[60];             /*   98 특이발행조건내용 (string 60) */
    char Bk_Holdy_Dd_Int_Pay_Decsn_Cd[1];       /*   99 은행휴무일이자지급결정코드 (string 1) */
    char Hbrdbnd_Yn[1];                         /*  100 신종자본증권여부 (string 1) */
    char Cond_Cap_Secu_Tp_Cd[1];                /*  101 조건부자본증권유형코드 (string 1) */
    char Coupn_Rt_Final_Yn[1];                  /*  102 표면이자율확정여부 (string 1) */
    char Bnd_Strip_Tp_Cd[1];                    /*  103 채권스트립구분코드 (string 1) */
    char Obj_Orgn_Bnd_Cd[12];                   /*  104 대상원본채권코드 (string 12) */
    char Strip_Nsprt_Bal[22];                   /*  105 스트립미분리잔액 (float 22) */
    char Infllnk_Yn[1];                         /*  106 물가연동여부 (string 1) */
    char Isu_Dd_Ref_Idx[11];                    /*  107 발행일참조지수 (float 11) */
    char Coupn_Rt_Decsn_Bas_Int_Cd[2];          /*  108 표면이자율결정기준금리코드 (string 2) */
    char Int_Rt_Decsn_Bas_Dd[8];                /*  109 이자율결정기준일자 (string 8) */
    char Bnd_Oddlotdd_Int_Bas_Tp_Cd[1];         /*  110 채권단수일이자기준구분코드 (string 1) */
    char Bk_Holdy_Dd_Int_Bas_Int_Cd[1];         /*  111 은행휴무일이자기준금리코드 (string 1) */
    char Bk_Holdy_Dd_Int_Cmp_Acrint_Rt[14];     /*  112 은행휴무일이자대비경과이자율 (float 14) */
    char Bk_Holdy_Princ_Pay_Dd_Decsn_Cd[1];     /*  113 은행휴무원금지급일결정코드 (string 1) */
    char Bk_Holdy_Dd_Princ_Bas_Int_Cd[1];       /*  114 은행휴무일원금기준금리코드 (string 1) */
    char Bk_Holdy_Dd_Princ_Acrint_Rt[14];       /*  115 은행휴무일원금경과이자율 (float 14) */
    char Arrantrd_Yn[1];                        /*  116 정리매매여부 (string 1) */
    char Retail_Bnd_Clss_Cd[2];                 /*  117 소매채권분류코드 (string 2) */
    char Srtsell_Lmt_Obj_Yn[1];                 /*  118 공매도제한대상여부 (string 1) */
    char Uplmtprc[11];                          /*  119 상한가 (float 11) */
    char Lwlmtprc[11];                          /*  120 하한가 (float 11) */
    char Prc_Unit_Rule_Id[10];                  /*  121 가격단위규칙ID (string 10) */
    char Invstwarn_Bnd_Tp_Cd[1];                /*  122 투자유의채권구분코드 (string 1) */
    char Split_Redempt_Dd[8];                   /*  123 분할상환일자 (string 8) */
} TRDESP50101_DATA;

#endif  /* _KRX_TRDESP50101_H */
