##########################################################################
# data SHM 정보 환경설정 (dshm.ini)
##########################################################################
#	dshm.ini는 real과 test가 동일함
#	Comment: 설명
#	Name: data SHM data name
#	Key: base key (4) + ',' + section (S:start, C:continue, E:end, O:one)
#		e.g. Key=0101,S -> PA (선물옵션주문체결)의 경우 data SHM segment의
#			key는 0x11010100고 해당 section은 segment의 시작부분임을 표시하며
#			여러 개의 process가 동시에 write할 경우 lock 처리를 위한 semaphore
#			의 key는 0x11010101이 됨
#-------------------------------------------------------------------------
#	* data SHM segment 및 semaphore의 key 구조
#	0x(1)(2)(3)(4)(5)(6)(7)(8) ->
#		(1)		- 2:PK system
#		(2)		- 1:Real, 2:Test
#		(3)(4)	- 부문. e.g. 01:PA, 02:PB, ..., 10:PJ, 11:PK, ...
#		(5)(6)	- 00:부문 SHM, 01~50:data SHM segment의 base key
#		(7)(8)	- 00:data SHM, 01~99:semaphore
#	e.g. 0x11010100 - PA (선물옵션주문체결), 선물옵션 data SHM
#		 0x11010101 - PA (선물옵션주문체결), 지수선물주문 data semaphore
#-------------------------------------------------------------------------
#	Fifo: FIFO count (equal to the number of processes that read this SHM)
#	Size: data size of a record
#		data size = size of a record - file header (62 bytes)
#						- data header (22) - LF (1)
#	Max: max record
##########################################################################
# 시세
##########################################################################
PB_CONF_START
Dshm_Count=0

PB_CONF_END

##########################################################################
# End of File (dshm.ini)
##########################################################################

