#########################################################################
# FILE 정보 환경설정 (file.ini)
##########################################################################
#	file.ini는 real과 test가 동일함
#	Name: SAM file name
#	Fifo: FIFO count (equal to the number of processes that read this file)
#	Size: data size of a record (one line in a file is a record)
#		data size = size of a record - file header (62 bytes)
#			- data header (22) - LF (1)
##########################################################################
# HATS_Basic
##########################################################################
##########################################################################
# 1201
# 채권일반처리호가(291), 채권조성처리호가(295)
# 주문은 55+     주문(254 or 255)
# 응답은 4+11+55+주문(254 or 255) => 325(Max)
# 주문은 거부가 날수있어서 "4+11"가 필요하다
# 1201에는 "4+11 + 주문전문"= 325(MAX), 4+11(회원처리호가는 0으로 set)
#
# 55바이트 업무헤더 추가 4+11 + 55 + 주문전문 = 325(MAX)
#
# 테스트용으로 qr이 수신해서 1201에 write하면 qs가 읽어서 처리하는 부분추가
##########################################################################
# 1401
# 채권체결결과(일반,조성)(317)
# 체결은 체결DATA(317)만, 헤더제외.. 헤더쓸일 없다.
##########################################################################
###################################################
#	시세수신처리
###################################################
#    A701K : 68  장운영TS
#    B601K : 462 일반채권, 국고채권 우선호가
#    A301K : 223 채권 체결
#    G701K : 643 일반채권, 국고채권 체결 + 우선호가
#    A601K : 57  채권 종목마감
#    I2000 : 10  Polling, Log만 File은 처리안함
###################################################
# A7/O6/B6/A3/G7/R1/A6/Q2/V1/I2 => 10305 (port)
###################################################
#    A001F(10301/11301) : 1318, 종목정보
#    A301F : 173, 파생체결
#    G701F : 431, 파생체결G7 (우선호가  5단계) 04F & 05F(제외)
#    B601F : 324, 파생우선호가 (우선호가  5단계) 04F & 05F(제외)
#    A701A : 68,  장운영정보(모든 A7공통.. All)
#    M401A : 83,  장운영스캐쥴
#    R101F : 359, 파생 장운영TS + 우선호가 (우선호가  5단계) 단일가 세션, 04F, 05F 제외
###################################################
PB_CONF_START
File_Count=8

File_1_Comment=채권주문송신01
File_1_Name=pb_1101_ts
File_1_Fifo=1
File_1_Size=400
File_End

File_2_Comment=채권일괄수신_KRX
File_2_Name=pb_1801_ts
File_2_Fifo=1
File_2_Size=600
File_End

File_3_Comment=주문송신_오류
File_3_Name=pb_1401_ts
File_3_Fifo=1
File_3_Size=400
File_End

File_4_Comment=회원처리호가및체결_송신
File_4_Name=pb_1402_ts
File_4_Fifo=1
File_4_Size=400
File_End

File_5_Comment=공개장운영정보_송신
File_5_Name=pb_1403_ts
File_5_Fifo=1
File_5_Size=200
File_End

File_6_Comment=일괄송신_RDS_송신
File_6_Name=pb_1411_ts
File_6_Fifo=1
File_6_Size=1300
File_End

File_7_Comment=채권체결DP송신
File_7_Name=pb_8111_ts
File_7_Fifo=1
File_7_Size=400
File_End

File_8_Comment=일괄수신결과송신
File_8_Name=pb_8116_ts
File_8_Fifo=1
File_8_Size=2048
File_End

PB_CONF_END
##########################################################################
# End of File (file.ini)
##########################################################################
