##########################################################################
# PROCESS 정보 환경 설정 (proc.ini)
##########################################################################
#	ID: process ID
#	Status: run or stop flag
#	Type: process type
#		MP:Manager Process, DD:Divide Division, TR:TCP Receive, TS:TCP Send,
#		TA:TCP Send/Receive, BR:DB Receive, BS:DB Send
#	IFN_1 ~ IFN_3: input file name 1 ~ 3
#	IDN_1 ~ IDN_3: input data SHM base name 1 ~ 3
#	FFN_1 ~ FFN_3: input FIFO name 1 ~ 3
#	ICN_1 ~ ICN_3: input cisam name 1 ~ 3
#	OFN_1 ~ OFN_9: output file name 1 ~ 9
#	ODN_1 ~ ODN_9: output data SHM base name 1 ~ 9
#	OCN_1 ~ OCN_3: output cisam name 1 ~ 3
#	Start_Time: start time (0000 ~ 2359)
#	End_Time: end time (0000 ~ 2359)
#	Time_Out: timeout (in second)
#	Delay: PS delay check time (in millisecond)
#	Data_Buf: data buffer 사용여부 (Y:사용)
#	Tcp1_Type: TCP/IP (mater daemon 방식) port type (M:master, S:service)
#	Tcp1_Port: TCP/IP (mater daemon 방식) port number
#	Tcp2_Primary: TCP/IP (직접접속 방식) dup ID and port number (primary)
#		e.g. Tcp2_Primary=0,6941 (0:dup ID, 6941:port number)
#	Tcp2_Backup: TCP/IP (직접접속 방식) dup ID and port number (backup)
#	Udp_Port: UDP/IP dup ID and port number
#	Dup_Id: dup ID of TCP2 or UDP port
##########################################################################
#	1:채권
#	2:파생주문처리
#	5:자동전략
#	6:조회처리
#	7:시세
#	8:Client관련
#	9:한도
#	3,4:예비
##########################################################################
PB_CONF_START
Proc_Count=18

Proc_1_Comment=채권KTS_시세수신
Proc_1_ID=pb_7102_ur
Proc_1_Status=S
Proc_1_Type=UR
Proc_1_Udp_Port=0,10402
Proc_1_Start_Time=0500
Proc_1_End_Time=2300
Proc_1_Time_Out=0
Proc_End

Proc_2_Comment=채권KTS_M4수신
Proc_2_ID=pb_7103_ur
Proc_2_Status=S
Proc_2_Type=UR
Proc_2_Udp_Port=0,10406
Proc_2_Start_Time=0500
Proc_2_End_Time=2300
Proc_2_Time_Out=0
Proc_End

#KRX 주문 (KTS)
Proc_3_Comment=주문수신
Proc_3_ID=pb_1301_tr
Proc_3_Status=S
Proc_3_Type=TS2
Proc_3_Tcp2_Primary=0,41001
Proc_3_OFN_1=pb_1101_ts
Proc_3_Start_Time=0600
Proc_3_End_Time=2300
Proc_3_Time_Out=0
Proc_End

Proc_4_Comment=채권주문송신(시장FEP)
Proc_4_ID=pb_1101_ts
Proc_4_LogonID=M60501O001
Proc_4_LogonPW=TTYwNTAxTzAwMQo=O001
Proc_4_Status=S
Proc_4_Type=TS2
Proc_4_Tcp2_Primary=0,37221
Proc_4_IFN_1=pb_1101_ts
Proc_4_FFN_1=pb_1101_ts1
Proc_4_OFN_1=pb_1401_ts
Proc_4_Start_Time=0730
Proc_4_End_Time=1900
Proc_4_Time_Out=0
Proc_End

Proc_5_Comment=주문송신(오류)
Proc_5_ID=pb_1401_ts
Proc_5_Status=S
Proc_5_Type=TS2
Proc_5_Tcp2_Primary=0,41002
Proc_5_IFN_1=pb_1401_ts
Proc_5_FFN_1=pb_1401_ts1
Proc_5_Start_Time=0600
Proc_5_End_Time=2300
Proc_5_Time_Out=0
Proc_End

# KRX 체결 (KTS)
Proc_6_Comment=채권응답체결수신(시장FEP)
Proc_6_ID=pb_1201_tr
Proc_6_LogonID=M60501T001
Proc_6_LogonPW=TTYwNTAxVDAwMQo=T001
Proc_6_Status=S
Proc_6_Type=TR2
Proc_6_Tcp2_Primary=0,57221
Proc_6_OFN_1=pb_1402_ts
Proc_6_Start_Time=0730
Proc_6_End_Time=1900
Proc_6_Time_Out=0
Proc_End

Proc_7_Comment=응답체결송신
Proc_7_ID=pb_1402_ts
Proc_7_Status=S
Proc_7_Type=TS2
Proc_7_Tcp2_Primary=0,41003
Proc_7_IFN_1=pb_1402_ts
Proc_7_FFN_1=pb_1402_ts1
Proc_7_Start_Time=0600
Proc_7_End_Time=2300
Proc_7_Time_Out=0
Proc_End

# KRX 체결DropCopy (KTS)
Proc_8_Comment=채권응답체결DP
Proc_8_ID=pb_1211_tr
Proc_8_LogonID=M60501D001
Proc_8_LogonPW=TTYwNTAxRDAwMQo=D001
Proc_8_Status=S
Proc_8_Type=TR2
Proc_8_Tcp2_Primary=0,61726
Proc_8_OFN_1=pb_8111_ts
Proc_8_Start_Time=0730
Proc_8_End_Time=1900
Proc_8_Time_Out=0
Proc_End

Proc_9_Comment=채권체결DP송신
Proc_9_ID=pb_8111_ts
Proc_9_Status=S
Proc_9_Type=TS2
Proc_9_Tcp2_Primary=0,32009
Proc_9_IFN_1=pb_8111_ts
Proc_9_FFN_1=pb_8111_ts1
Proc_9_Start_Time=0600
Proc_9_End_Time=2300
Proc_9_Time_Out=0
Proc_End

# KRX 공개장운영(KTS)
Proc_10_Comment=KTS_Market_Info
Proc_10_ID=pb_1601_tr
Proc_10_LogonID=M60501M001
Proc_10_LogonPW=TTYwNTAxTTAwMQo=M001
Proc_10_Status=S
Proc_10_Type=TS2
Proc_10_Tcp2_Primary=0,61725
Proc_10_OFN_1=pb_1403_ts
Proc_10_Start_Time=0800
Proc_10_End_Time=1810
Proc_10_Time_Out=65
Proc_End

Proc_11_Comment=공개장운영정보
Proc_11_ID=pb_1403_ts
Proc_11_Status=S
Proc_11_Type=TS2
Proc_11_Tcp2_Primary=0,41004
Proc_11_IFN_1=pb_1403_ts
Proc_11_FFN_1=pb_1403_ts1
Proc_11_Start_Time=0600
Proc_11_End_Time=2300
Proc_11_Time_Out=0
Proc_End

# KRX 일괄 송신(우리는 수신)
Proc_12_Comment=채권TCP_RDS수신
Proc_12_ID=pb_7801_tr
Proc_12_LogonID=M00501S001
Proc_12_LogonPW=TTAwNTAxUzAwMQo=S001
Proc_12_Status=S
Proc_12_Type=TR2
Proc_12_Tcp2_Primary=0,63725
Proc_12_OFN_1=pb_1411_ts
Proc_12_Start_Time=0800
Proc_12_End_Time=0230
Proc_12_Time_Out=0
Proc_End

Proc_13_Comment=일괄송신_RDS
Proc_13_ID=pb_1411_ts
Proc_13_Status=S
Proc_13_Type=TS2
Proc_13_Tcp2_Primary=0,41005
Proc_13_IFN_1=pb_1411_ts
Proc_13_FFN_1=pb_1411_ts1
Proc_13_Start_Time=0600
Proc_13_End_Time=0200
Proc_13_Time_Out=0
Proc_End

# KRX 일괄 수신(우리는 송신)
Proc_14_Comment=일괄수신_지점정보
Proc_14_ID=pb_8211_tr
Proc_14_Status=S
Proc_14_Type=TS2
Proc_14_Tcp2_Primary=0,32019
Proc_14_OFN_1=pb_1801_ts
Proc_14_Start_Time=0600
Proc_14_End_Time=2300
Proc_14_Time_Out=0
Proc_End

Proc_15_Comment=채권일괄수신
Proc_15_ID=pb_1801_ts
Proc_15_LogonID=M00501R001
Proc_15_LogonPW=TTAwNTAxUjAwMQo=R001
Proc_15_Status=S
Proc_15_Type=TR2
Proc_15_Tcp2_Primary=0,63724
Proc_15_IFN_1=pb_1801_ts
Proc_15_OFN_1=pb_8116_ts
Proc_15_Start_Time=0700
Proc_15_End_Time=0200
Proc_15_Time_Out=0
Proc_End

Proc_16_Comment=일괄송신_RDS
Proc_16_ID=pb_8116_ts
Proc_16_Status=S
Proc_16_Type=TS2
Proc_16_Tcp2_Primary=0,32016
Proc_16_IFN_1=pb_8116_ts
Proc_16_FFN_1=pb_8116_ts1
Proc_16_Start_Time=0600
Proc_16_End_Time=2300
Proc_16_Time_Out=0
Proc_End

#################################################################
#관리
#################################################################
Proc_17_Comment=SyncManager
Proc_17_ID=pb_1001_mp
Proc_17_Status=S
Proc_17_Type=MP
#S:0430,E:0400
Proc_17_Start_Time=0500
Proc_17_End_Time=0330
Proc_End

Proc_18_Comment=LogManager
Proc_18_ID=pb_2001_mp
Proc_18_Status=R
Proc_18_Type=MP
#S:0430,E:0400
Proc_18_Start_Time=0500
Proc_18_End_Time=0330
Proc_End

PB_CONF_END

##########################################################################
# TCPIP업무접속
##########################################################################

##########################################################################
# End of File (proc.ini)
##########################################################################
