###########################################################################
# TCP1 (PORT DAEMON 방식) 정보 환경 설정 (tcp1.ini)
###########################################################################
#	Ip: server ip address (out of use)
#		All numbers supplied as parts in dot notation can be decimal, octal,
#		or hexadecimal, as specified in the C language (i.e., a leading 0x or
#		0X implies hexadecimal; a leading 0 implies octal; otherwise, the
#		number is interpreted as decimal).
#		e.g. 130.100.241.56 (correct), 130.100.241.056 (false)
#	Port: master port number
#	SPort01 ~ SPort09: service port number 1 ~ 9
###########################################################################
# TCP업무접속
###########################################################################
PW_CONF_START
Tcp1_Count=2

Tcp1_1_Comment=TCP업무접속(P)
Tcp1_1_Port=35010
Tcp1_1_SPort01=35011
Tcp1_1_SPort02=35012
Tcp1_1_SPort03=35013
Tcp1_1_SPort04=35014
Tcp1_1_SPort05=35015
Tcp1_1_SPort06=35016
Tcp1_1_SPort07=35017
Tcp1_1_SPort08=35018
Tcp1_1_SPort09=35019
Tcp1_End

Tcp1_2_Comment=TCP업무접속(B)
Tcp1_2_Port=45010
Tcp1_2_SPort01=45011
Tcp1_2_SPort02=45012
Tcp1_2_SPort03=45013
Tcp1_2_SPort04=45014
Tcp1_2_SPort05=45015
Tcp1_2_SPort06=45016
Tcp1_2_SPort07=45017
Tcp1_2_SPort08=45018
Tcp1_2_SPort09=45019
Tcp1_End

PW_CONF_END

###########################################################################
# End of File (tcp1.ini)
###########################################################################

