##########################################################################
# UDPIP 정보 환경 설정 (udpip.ini)
##########################################################################
#	Comment: 설명 (max 40 bytes)
#	Ip_1 ~ Ip_20: server ip address
#		All numbers supplied as parts in dot notation can be decimal, octal,
#		or hexadecimal, as specified in the C language (i.e., a leading 0x or
#		0X implies hexadecimal; a leading 0 implies octal; otherwise, the
#		number is interpreted as decimal).
#		e.g. 172.30.220.151 (correct), 172.030.220.151 (false)
#	Dup_Id: avoiding duplication of port
#	Port_1 ~ Port_20: server port number
##########################################################################
# 선물옵션주문체결
##########################################################################
PB_CONF_START
Udpip_Count=2

######################################################################
#  채권100M "운영_10301/TEST_11301/재전송_20301" 
#  - A701K/B601K/A301K/G701K/A601K/I2000
#            운영_11412/TEST_12412/재전송_20401
#  - M4/R3/R4:장운영스케줄공개/회원제재해제공개/일반채권 결제적용 기준환율 공개
#            운영_11406/TEST_12406/재전송_20401
#   <시세>
#	8M   : 233.38.231.152, 10402/11402/12402/20401
#	512K : 233.38.231.162, 10412/11412/12412/20401
#	<장운영>
#	8M   : 233.38.231.153, 10406/11406/12406/20401
#	512K : 233.38.231.153, 10406/11406/12406/20401
#	
######################################################################
Udpip_1_Comment=채권시세수신
Udpip_1_Ip_1=233.38.231.91
Udpip_1_Port_1=10402
Udpip_End

Udpip_2_Comment=채권장운영수신
Udpip_2_Ip_1=233.38.231.153
Udpip_2_Port_1=10406
Udpip_End

PB_CONF_END

##########################################################################
# End of File (udpip.ini)
##########################################################################
