[MODE]
test_mode=0   // 1: test 0: 운영
init_memory=1 // 1: 전략메모리reset / 주문번호 / 세트 정보    0: // 초기화 없음.
day_end_time=160000 // 주간전략중단시간- 주간선물장마감 기준으로 중단하도록 수정  
ngt_end_time=060000 // 야간전략중단시간- 야간선물장마감 기준으로 중단하도록 수정  

[LOG]
log_level=0   // 0:ERR 1:WAR 2:INF 3:DBG
log_file=/fslog/win

## --- 전략 메모리 : 주간
[STRATEGY_DAY]
strat_shm_key=0xaa001001
strat_shm_size=65536
max_strats=200
sets_per_strat=2000

## --- 전략 메모리 :야간 (사용X 주간 통합) 
[STRATEGY_NGT] 
strat_shm_key=0xaa001002
strat_shm_size=65536
max_strats=200
sets_per_strat=2000

##--- 주문기본 번호대(선물:6,200,001~7,000,000 현물: 4000000000~ )
[ORDER_ID]
futoid=6200001
futmaxoid=7000000
nhspotoid=4000000001
nhspotmaxoid=4100000000
jpmspotoid=4200000001
jpmspotmaxoid=4300000000
shspotoid=4300000001
shspotmaxoid=4400000000

[FUT_OID_SHM]
fut_oid_shm_key=0xaa002001
fut_oid_shm_size=65

[SPOT_OID_SHM]
spot_oid_shm_size=65
nhspot_oid_shm_key=0xaa002002
jpmspot_oid_shm_key=0xaa002003
shspot_oid_shm_key=0xaa002004

## --- 현물 주문 전송
[NH_ORDER]
order_msg_key=0xff170010
order_msg_mtype=100

[JPM_ORDER]
order_msg_key=0xff170070
order_msg_mtype=100

[SH_ORDER]
order_msg_key=0xff170050
order_msg_mtype=100

## --- 선물 주문 전송
[KRX_ORDER_DAY]
order_msg_key=0x22000011
order_msg_mtype=100

[KRX_ORDER_NGT]
order_msg_key=0x22000021
order_msg_mtype=100

## --- 선물/현물주문 후처리 큐 전송
[ORDERLOGQ] 
orderlogq_fut_msg_key_text=FTRS_AFPRCSS_QUE
orderlogq_fut_msg_mtype=100

orderlogq_spot_msg_key=0x23000125
orderlogq_spot_msg_mtype=100

orderlogq_jpm_msg_key=0x23000130
orderlogq_jpm_msg_mtype=100

orderlogq_sh_msg_key=0x23000135
orderlogq_sh_msg_mtype=100
