##########################################################################
# 부문별 DAEMON 정보 환경 설정 (daemon.ini)
##########################################################################
#	ID: daemon process ID
#	Start_Time: start time (0000 ~ 2359)
#	End_Time: end time (0000 ~ 2359)
#	Date_Flag: work date flag
#		1:D~D, 2:D~D+1, 3:D+1~D+1, 4:D-1~D, 5:D-1~D-1, 9:run continuously
#		(D = work date)
#        00:00              00:00               00:00               00:00
#          |     < D - 1 >    |       < D >       |     < D + 1 >     |
#       ---+------------------+-------------------+-------------------+---
#                               |_______1_______|
#                     |_______4_______|   |_______2_______|
#            |_______5_______|                      |_______3_______|
#	(연속 기동 부문은 Date_Flag=9, Start_Time=0000, End_Time=0000로 set)
#	Compact_Days: 지정된 일수 이전의 data와 log를 삭제함
#	Status: run or stop flag (0:not run 1:run)
#	FIFO: FIFO name
#	Proc_Count: number of processes (5의 배수로 지정할 것)
#	File_Count: number of files
#	Dshm_Count: number of data SHM
#	Cisam_Count: number of cisam files
#	Tcp1_Count: number of TCP/IP master ports (port daemon 방식)
#	Tcp2_Count: number of TCP/IP ports (직접접속 방식)
#	Udpip_Count: number of UDP/IP ports
#	Sise_Count: number of sise TR
#	Data_Count: number of processes that use SHM data buffer
#	Accno_Count: number of account
#	Shm_Log: SHM log flag (1:use SHM (delayed) log)
##########################################################################
DAEMON_CONF_START

Daemon_A_Comment=MERITZ
Daemon_A_ID=pa_daemon_mp
Daemon_A_Start_Time=0300
#Daemon_A_End_Time=2330
Daemon_A_End_Time=0200
Daemon_A_Date_Flag=2
Daemon_A_Compact_Days=4
Daemon_A_Status=1
Daemon_A_FIFO=pa_FIFO
Daemon_A_Shm_Log=1
Daemon_A_Proc_Count=115
Daemon_A_File_Count=80
Daemon_A_Dshm_Count=45
Daemon_A_Tcp2_Count=30
Daemon_A_Udpip_Count=15
Daemon_A_Data_Count=45
Daemon_End

Daemon_B_Comment=HATS_H
Daemon_End

Daemon_C_Comment=예비
Daemon_End

Daemon_D_Comment=예비
Daemon_End

Daemon_E_Comment=예비
Daemon_End

Daemon_F_Comment=예비
Daemon_End

Daemon_G_Comment=예비
Daemon_End

Daemon_H_Comment=예비
Daemon_End

Daemon_I_Comment=예비
Daemon_End

Daemon_J_Comment=예비
Daemon_End

Daemon_K_Comment=예비
Daemon_End

Daemon_L_Comment=예비
Daemon_End

Daemon_M_Comment=예비
Daemon_End

Daemon_N_Comment=예비
Daemon_End

Daemon_O_Comment=예비
Daemon_End

Daemon_P_Comment=예비
Daemon_End

Daemon_Q_Comment=예비
Daemon_End

Daemon_R_Comment=예비
Daemon_End

Daemon_S_Comment=예비
Daemon_End

Daemon_T_Comment=예비
Daemon_End

Daemon_U_Comment=예비
Daemon_End

Daemon_V_Comment=예비
Daemon_End

Daemon_W_Comment=TCPIP업무접속
Daemon_End

Daemon_X_Comment=Utility
Daemon_X_FIFO=px_FIFO
Daemon_End

Daemon_Y_Comment=운영
Daemon_Y_FIFO=py_FIFO
Daemon_End

Daemon_Z_Comment=관리
Daemon_Z_Start_Time=0000
Daemon_Z_End_Time=0000
Daemon_Z_Compact_Days=3
Daemon_Z_FIFO=pz_FIFO
Daemon_End

DAEMON_CONF_END

##########################################################################
# End of File (daemon.ini)
##########################################################################

