fname=TSKEIMU52.csv
fpath=$PWD/$fname
logfile=$PWD/mig.log 

echo $DBPASS
DBPASS=${DBPASS//\\/}
echo $DBPASS

db2 CONNECT TO DSKEIT USER KEI000 USING $DBPASS
db2 quit
exit

echo "Save Data from ASIS Table"
echo ""
db2 "EXPORT TO '$fpath' OF DEL MODIFIED BY CHARDEL''
		MESSAGES '$logfile'
		SELECT	 GROUP_CO_CD
				,FX_PRDCT_CD
				,'1'				-- NEW : MRKUP_DSTCD
				,REGI_YMD
				,RGST_TIME
				,BID_LAST_PRC
				,OFFER_LAST_PRC
				,MID_LAST_PRC
				,BID_OPEN_PRC
				,BID_HIGH_PRC
				,BID_LOW_PRC
				,OFFER_OPEN_PRC
				,OFFER_HIGH_PRC
				,OFFER_LOW_PRC
				,MID_OPEN_PRC
				,MID_HIGH_PRC
				,MID_LOW_PRC
				,'090000000'		-- NEW : OPEN_PRC_TIME
				,'090000000'		-- NEW : HIGH_PRC_TIME
				,'090000000'		-- NEW : LOW_PRC_TIME
				,PRDAT_CNTST_PRC
				,UPDWN_RATO
				,SYS_LAST_PRCSS_YMS
				,SYS_LAST_UNO
		  FROM	INST1.TSKEIMU52
		 WHERE	REGI_YMD = '20231201'
"

db2 connect reset

