#########################################################################
# FILE 정보 환경설정 (file.ini)
##########################################################################
#	file.ini는 real과 test가 동일함
#	Name: SAM file name
#	Fifo: FIFO count (equal to the number of processes that read this file)
#	Size: data size of a record (one line in a file is a record)
#		data size = size of a record - file header (62 bytes)
#			- data header (22) - LF (1)
##########################################################################
# HATS_Basic
##########################################################################
##########################################################################
# 1201
# 채권일반처리호가(291), 채권조성처리호가(295)
# 주문은 55+     주문(254 or 255)
# 응답은 4+11+55+주문(254 or 255) => 325(Max)
# 주문은 거부가 날수있어서 "4+11"가 필요하다
# 1201에는 "4+11 + 주문전문"= 325(MAX), 4+11(회원처리호가는 0으로 set)
#
# 55바이트 업무헤더 추가 4+11 + 55 + 주문전문 = 325(MAX)
#
# 테스트용으로 qr이 수신해서 1201에 write하면 qs가 읽어서 처리하는 부분추가
##########################################################################
# 1401
# 채권체결결과(일반,조성)(317)
# 체결은 체결DATA(317)만, 헤더제외.. 헤더쓸일 없다.
##########################################################################
###################################################
#	시세수신처리
###################################################
#    A701K : 68  장운영TS
#    B601K : 462 일반채권, 국고채권 우선호가
#    A301K : 223 채권 체결
#    G701K : 643 일반채권, 국고채권 체결 + 우선호가
#    A601K : 57  채권 종목마감
#    I2000 : 10  Polling, Log만 File은 처리안함
###################################################
# A7/O6/B6/A3/G7/R1/A6/Q2/V1/I2 => 10305 (port)
###################################################
#    A001F(10301/11301) : 1318, 종목정보
#    A301F : 173, 파생체결
#    G701F : 431, 파생체결G7 (우선호가  5단계) 04F & 05F(제외)
#    B601F : 324, 파생우선호가 (우선호가  5단계) 04F & 05F(제외)
#    A701A : 68,  장운영정보(모든 A7공통.. All)
#    M401A : 83,  장운영스캐쥴
#    R101F : 359, 파생 장운영TS + 우선호가 (우선호가  5단계) 단일가 세션, 04F, 05F 제외
###################################################
PA_CONF_START
File_Count=119

File_1_Comment=주문송신
File_1_Name=pa_1301_ts
File_1_Fifo=1
File_1_Size=400
File_End

File_2_Comment=채권주문응답
File_2_Name=pa_1201_mp
File_2_Fifo=3
File_2_Size=400
File_End

File_3_Comment=채권체결
File_3_Name=pa_1401_mp
File_3_Fifo=3
File_3_Size=400
File_End

File_4_Comment=채권체결재처리
File_4_Name=pa_1492_mp
File_4_Fifo=1
File_4_Size=400
File_End

File_5_Comment=파생주문응답
File_5_Name=pa_2201_mp
File_5_Fifo=3
File_5_Size=200
File_End

File_6_Comment=파생체결
File_6_Name=pa_2401_mp
File_6_Fifo=3
File_6_Size=200
File_End

File_7_Comment=파생체결재처리
File_7_Name=pa_2492_mp
File_7_Fifo=1
File_7_Size=200
File_End

File_8_Comment=KTS_장운영_공개장운영등
File_8_Name=pa_1601_mp
File_8_Fifo=2
File_8_Size=200
File_End

File_9_Comment=KTS_장운영_종목마감등
File_9_Name=pa_1602_mp
File_9_Fifo=1
File_9_Size=150
File_End

File_10_Comment=DEV_Markert_Info
File_10_Name=pa_2601_mp
File_10_Fifo=2
File_10_Size=200
File_End

File_11_Comment=조회요구
File_11_Name=pa_6001_mp
File_11_Fifo=1
File_11_Size=2048
File_End

File_12_Comment=Client송신
File_12_Name=pa_8101_ts
File_12_Fifo=2
File_12_Size=2048
File_End

File_13_Comment=채권체결DP송신
File_13_Name=pa_8111_ts
File_13_Fifo=1
File_13_Size=400
File_End

File_14_Comment=일괄수신결과송신
File_14_Name=pa_8116_ts
File_14_Fifo=1
File_14_Size=2048
File_End

#	Auto 체결반응용
File_15_Comment=채권Auto용(체결반응)
File_15_Name=pa_7102_ur
File_15_Fifo=1
File_15_Size=1
File_End

File_16_Comment=채권Auto용(호가반응)
File_16_Name=pa_7103_ur
File_16_Fifo=1
File_16_Size=1
File_End

File_17_Comment=금융파생Auto용(체결반응)
File_17_Name=pa_7202_ur
File_17_Fifo=1
File_17_Size=1
File_End

File_18_Comment=금융파생Auto용(호가반응)
File_18_Name=pa_7203_ur
File_18_Fifo=1
File_18_Size=1
File_End

File_19_Comment=채권KTS시세
File_19_Name=pa_7102_dd
File_19_Fifo=3
File_19_Size=700
File_End

File_20_Comment=채권KTS_M4
File_20_Name=pa_7103_dd
File_20_Fifo=2
File_20_Size=100
File_End

File_21_Comment=채권종목정보_RDS
File_21_Name=pa_7181_dd
File_21_Fifo=1
File_21_Size=1300
File_End

File_22_Comment=채권KTS종목정보_RDS
File_22_Name=pa_7182_dd
File_22_Fifo=1
File_22_Size=450
File_End

File_23_Comment=채권일괄수신_KRX
File_23_Name=pa_1801_ts
File_23_Fifo=1
File_23_Size=600
File_End

File_24_Comment=금융파생기본
File_24_Name=pa_7201_dd
File_24_Fifo=2
File_24_Size=1400
File_End

File_25_Comment=금융파생시세수신
File_25_Name=pa_7202_dd
File_25_Fifo=3
File_25_Size=450
File_End

File_26_Comment=금융파생기타시세수신
File_26_Name=pa_7203_dd
File_26_Fifo=2
File_26_Size=400
File_End

File_27_Comment=채권종목정보_RDS수신
File_27_Name=pa_7801_dd
File_27_Fifo=2
File_27_Size=1300
File_End

File_28_Comment=채권KTS종목정보_RDS수신
File_28_Name=pa_7802_dd
File_28_Fifo=2
File_28_Size=450
File_End

File_29_Comment=채권가격단위규칙_RDS수신
File_29_Name=pa_7803_dd
File_29_Fifo=1
File_29_Size=100
File_End

File_30_Comment=한도자동로직관리
File_30_Name=pa_9001_mp
File_30_Fifo=1
File_30_Size=2048
File_End

File_31_Comment=금융Auto용(체결반응)
File_31_Name=pa_7402_ur
File_31_Fifo=1
File_31_Size=10
File_End

File_32_Comment=FX주문응답
File_32_Name=pa_4201_mp
File_32_Fifo=2
File_32_Size=1024
File_End

File_33_Comment=FX체결
File_33_Name=pa_4401_mp
File_33_Fifo=2
File_33_Size=1024
File_End

File_34_Comment=FX체결재처리
File_34_Name=pa_4492_mp
File_34_Fifo=1
File_34_Size=1024
File_End

File_35_Comment=채권응답송신
File_35_Name=pa_5201_qs
File_35_Fifo=1
File_35_Size=400
File_End

File_36_Comment=채권체결송신
File_36_Name=pa_5401_qs
File_36_Fifo=1
File_36_Size=400
File_End

File_37_Comment=파생응답송신
File_37_Name=pa_5211_qs
File_37_Fifo=1
File_37_Size=200
File_End

File_38_Comment=금융파생체결송신
File_38_Name=pa_5411_qs
File_38_Fifo=1
File_38_Size=200
File_End

File_39_Comment=전략Auto용(체결반응)
File_39_Name=pa_55101mp
File_39_Fifo=1
File_39_Size=1
File_End

File_40_Comment=전략Auto용(체결반응)
File_40_Name=pa_55102mp
File_40_Fifo=1
File_40_Size=1
File_End

File_41_Comment=전략Auto용(체결반응)
File_41_Name=pa_55103mp
File_41_Fifo=1
File_41_Size=1
File_End

File_42_Comment=전략Auto용(체결반응)
File_42_Name=pa_55104mp
File_42_Fifo=1
File_42_Size=1
File_End

File_43_Comment=전략Auto용(체결반응)
File_43_Name=pa_55105mp
File_43_Fifo=1
File_43_Size=1
File_End

File_44_Comment=전략Auto용(체결반응)
File_44_Name=pa_55106mp
File_44_Fifo=1
File_44_Size=1
File_End

File_45_Comment=전략Auto용(체결반응)
File_45_Name=pa_55107mp
File_45_Fifo=1
File_45_Size=1
File_End

File_46_Comment=전략Auto용(체결반응)
File_46_Name=pa_55108mp
File_46_Fifo=1
File_46_Size=1
File_End

File_47_Comment=전략Auto용(체결반응)
File_47_Name=pa_55109mp
File_47_Fifo=1
File_47_Size=1
File_End

File_48_Comment=전략Auto용(체결반응)
File_48_Name=pa_55110mp
File_48_Fifo=1
File_48_Size=1
File_End

File_49_Comment=전략Auto용(체결반응)
File_49_Name=pa_55201mp
File_49_Fifo=1
File_49_Size=1
File_End

File_50_Comment=전략Auto용(체결반응)
File_50_Name=pa_55202mp
File_50_Fifo=1
File_50_Size=1
File_End

File_51_Comment=전략Auto용(체결반응)
File_51_Name=pa_55203mp
File_51_Fifo=1
File_51_Size=1
File_End

File_52_Comment=전략Auto용(체결반응)
File_52_Name=pa_55204mp
File_52_Fifo=1
File_52_Size=1
File_End

File_53_Comment=전략Auto용(체결반응)
File_53_Name=pa_55205mp
File_53_Fifo=1
File_53_Size=1
File_End

File_54_Comment=전략Auto용(체결반응)
File_54_Name=pa_55206mp
File_54_Fifo=1
File_54_Size=1
File_End

File_55_Comment=전략Auto용(체결반응)
File_55_Name=pa_55207mp
File_55_Fifo=1
File_55_Size=1
File_End

File_56_Comment=전략Auto용(체결반응)
File_56_Name=pa_55208mp
File_56_Fifo=1
File_56_Size=1
File_End

File_57_Comment=전략Auto용(체결반응)
File_57_Name=pa_55209mp
File_57_Fifo=1
File_57_Size=1
File_End

File_58_Comment=전략Auto용(체결반응)
File_58_Name=pa_55210mp
File_58_Fifo=1
File_58_Size=1
File_End

File_59_Comment=전략Auto용(체결반응)
File_59_Name=pa_55301mp
File_59_Fifo=1
File_59_Size=1
File_End

File_60_Comment=전략Auto용(체결반응)
File_60_Name=pa_55302mp
File_60_Fifo=1
File_60_Size=1
File_End

File_61_Comment=전략Auto용(체결반응)
File_61_Name=pa_55303mp
File_61_Fifo=1
File_61_Size=1
File_End

File_62_Comment=전략Auto용(체결반응)
File_62_Name=pa_55304mp
File_62_Fifo=1
File_62_Size=1
File_End

File_63_Comment=전략Auto용(체결반응)
File_63_Name=pa_55305mp
File_63_Fifo=1
File_63_Size=1
File_End

File_64_Comment=전략Auto용(체결반응)
File_64_Name=pa_55306mp
File_64_Fifo=1
File_64_Size=1
File_End

File_65_Comment=전략Auto용(체결반응)
File_65_Name=pa_55307mp
File_65_Fifo=1
File_65_Size=1
File_End

File_66_Comment=전략Auto용(체결반응)
File_66_Name=pa_55308mp
File_66_Fifo=1
File_66_Size=1
File_End

File_67_Comment=전략Auto용(체결반응)
File_67_Name=pa_55309mp
File_67_Fifo=1
File_67_Size=1
File_End

File_68_Comment=전략Auto용(체결반응)
File_68_Name=pa_55310mp
File_68_Fifo=1
File_68_Size=1
File_End

File_69_Comment=전략Auto용(체결반응)
File_69_Name=pa_55401mp
File_69_Fifo=1
File_69_Size=1
File_End

File_70_Comment=전략Auto용(체결반응)
File_70_Name=pa_55402mp
File_70_Fifo=1
File_70_Size=1
File_End

File_71_Comment=전략Auto용(체결반응)
File_71_Name=pa_55403mp
File_71_Fifo=1
File_71_Size=1
File_End

File_72_Comment=전략Auto용(체결반응)
File_72_Name=pa_55404mp
File_72_Fifo=1
File_72_Size=1
File_End

File_73_Comment=전략Auto용(체결반응)
File_73_Name=pa_55405mp
File_73_Fifo=1
File_73_Size=1
File_End

File_74_Comment=전략Auto용(체결반응)
File_74_Name=pa_55406mp
File_74_Fifo=1
File_74_Size=1
File_End

File_75_Comment=전략Auto용(체결반응)
File_75_Name=pa_55407mp
File_75_Fifo=1
File_75_Size=1
File_End

File_76_Comment=전략Auto용(체결반응)
File_76_Name=pa_55408mp
File_76_Fifo=1
File_76_Size=1
File_End

File_77_Comment=전략Auto용(체결반응)
File_77_Name=pa_55409mp
File_77_Fifo=1
File_77_Size=1
File_End

File_78_Comment=전략Auto용(체결반응)
File_78_Name=pa_55410mp
File_78_Fifo=1
File_78_Size=1
File_End

########################################
File_79_Comment=채권주문송신01
File_79_Name=pa_1101_ts
File_79_Fifo=1
File_79_Size=400
File_End

File_80_Comment=자동주문0101
File_80_Name=pa_50101mp
File_80_Fifo=1
File_80_Size=2048
File_End

File_81_Comment=자동주문0102
File_81_Name=pa_50102mp
File_81_Fifo=1
File_81_Size=2048
File_End

File_82_Comment=자동주문0103
File_82_Name=pa_50103mp
File_82_Fifo=1
File_82_Size=2048
File_End

File_83_Comment=자동주문0104
File_83_Name=pa_50104mp
File_83_Fifo=1
File_83_Size=2048
File_End

File_84_Comment=자동주문0105
File_84_Name=pa_50105mp
File_84_Fifo=1
File_84_Size=2048
File_End

File_85_Comment=자동주문0106
File_85_Name=pa_50106mp
File_85_Fifo=1
File_85_Size=2048
File_End

File_86_Comment=자동주문0107
File_86_Name=pa_50107mp
File_86_Fifo=1
File_86_Size=2048
File_End

File_87_Comment=자동주문0108
File_87_Name=pa_50108mp
File_87_Fifo=1
File_87_Size=2048
File_End

File_88_Comment=자동주문0109
File_88_Name=pa_50109mp
File_88_Fifo=1
File_88_Size=2048
File_End

File_89_Comment=자동주문0110
File_89_Name=pa_50110mp
File_89_Fifo=1
File_89_Size=2048
File_End

File_90_Comment=자동주문0201
File_90_Name=pa_50201mp
File_90_Fifo=1
File_90_Size=2048
File_End

File_91_Comment=자동주문0202
File_91_Name=pa_50202mp
File_91_Fifo=1
File_91_Size=2048
File_End

File_92_Comment=자동주문0203
File_92_Name=pa_50203mp
File_92_Fifo=1
File_92_Size=2048
File_End

File_93_Comment=자동주문0204
File_93_Name=pa_50204mp
File_93_Fifo=1
File_93_Size=2048
File_End

File_94_Comment=자동주문0205
File_94_Name=pa_50205mp
File_94_Fifo=1
File_94_Size=2048
File_End

File_95_Comment=자동주문0206
File_95_Name=pa_50206mp
File_95_Fifo=1
File_95_Size=2048
File_End

File_96_Comment=자동주문0207
File_96_Name=pa_50207mp
File_96_Fifo=1
File_96_Size=2048
File_End

File_97_Comment=자동주문0208
File_97_Name=pa_50208mp
File_97_Fifo=1
File_97_Size=2048
File_End

File_98_Comment=자동주문0209
File_98_Name=pa_50209mp
File_98_Fifo=1
File_98_Size=2048
File_End

File_99_Comment=자동주문0210
File_99_Name=pa_50210mp
File_99_Fifo=1
File_99_Size=2048
File_End

File_100_Comment=자동주문0301
File_100_Name=pa_50301mp
File_100_Fifo=1
File_100_Size=2048
File_End

File_101_Comment=자동주문0302
File_101_Name=pa_50302mp
File_101_Fifo=1
File_101_Size=2048
File_End

File_102_Comment=자동주문0303
File_102_Name=pa_50303mp
File_102_Fifo=1
File_102_Size=2048
File_End

File_103_Comment=자동주문0304
File_103_Name=pa_50304mp
File_103_Fifo=1
File_103_Size=2048
File_End

File_104_Comment=자동주문0305
File_104_Name=pa_50305mp
File_104_Fifo=1
File_104_Size=2048
File_End

File_105_Comment=자동주문0306
File_105_Name=pa_50306mp
File_105_Fifo=1
File_105_Size=2048
File_End

File_106_Comment=자동주문0307
File_106_Name=pa_50307mp
File_106_Fifo=1
File_106_Size=2048
File_End

File_107_Comment=자동주문0308
File_107_Name=pa_50308mp
File_107_Fifo=1
File_107_Size=2048
File_End

File_108_Comment=자동주문0309
File_108_Name=pa_50309mp
File_108_Fifo=1
File_108_Size=2048
File_End

File_109_Comment=자동주문0310
File_109_Name=pa_50310mp
File_109_Fifo=1
File_109_Size=2048
File_End

File_110_Comment=자동주문0401
File_110_Name=pa_50401mp
File_110_Fifo=1
File_110_Size=2048
File_End

File_111_Comment=자동주문0402
File_111_Name=pa_50402mp
File_111_Fifo=1
File_111_Size=2048
File_End

File_112_Comment=자동주문0403
File_112_Name=pa_50403mp
File_112_Fifo=1
File_112_Size=2048
File_End

File_113_Comment=자동주문0404
File_113_Name=pa_50404mp
File_113_Fifo=1
File_113_Size=2048
File_End

File_114_Comment=자동주문0405
File_114_Name=pa_50405mp
File_114_Fifo=1
File_114_Size=2048
File_End

File_115_Comment=자동주문0406
File_115_Name=pa_50406mp
File_115_Fifo=1
File_115_Size=2048
File_End

File_116_Comment=자동주문0407
File_116_Name=pa_50407mp
File_116_Fifo=1
File_116_Size=2048
File_End

File_117_Comment=자동주문0408
File_117_Name=pa_50408mp
File_117_Fifo=1
File_117_Size=2048
File_End

File_118_Comment=자동주문0409
File_118_Name=pa_50409mp
File_118_Fifo=1
File_118_Size=2048
File_End

File_119_Comment=자동주문0410
File_119_Name=pa_50410mp
File_119_Fifo=1
File_119_Size=2048
File_End

PA_CONF_END

##########################################################################
# End of File (file.ini)
##########################################################################

