##########################################################################
# TCP2 (직접접속 방식) 정보 환경 설정 (tcp2.ini)
##########################################################################
#	Ip: server ip address
#		All numbers supplied as parts in dot notation can be decimal, octal,
#		or hexadecimal, as specified in the C language (i.e., a leading 0x or
#		0X implies hexadecimal; a leading 0 implies octal; otherwise, the
#		number is interpreted as decimal).
#		e.g. 172.30.220.151 (correct), 172.030.220.151 (false)
#	Dup_Id: avoiding duplication of port
#	Port: port number
##########################################################################
# HATS_B (PA)
##########################################################################
PA_CONF_START
Tcp2_Count=34

# 금융파생시세A0 (TCP)
Tcp2_1_Comment=금융상품A0
Tcp2_1_Ip=192.168.151.11
Tcp2_1_Dup_Id=0
Tcp2_1_Port=16518
Tcp2_End

# 금융파생시세 (TCP)
Tcp2_2_Comment=금융상품시세
Tcp2_2_Ip=192.168.151.11
Tcp2_2_Dup_Id=0
Tcp2_2_Port=16512
Tcp2_End

Tcp2_3_Comment=금융상품A0수신
Tcp2_3_Ip=233.38.231.91
Tcp2_3_Dup_Id=0
Tcp2_3_Port=10301
Tcp2_End

Tcp2_4_Comment=금융상품시세수신
Tcp2_4_Ip=233.38.231.92
Tcp2_4_Dup_Id=0
Tcp2_4_Port=10306
Tcp2_End

# 금융파생주문 (TCP)
Tcp2_5_Comment=금융상품파생주문
Tcp2_5_Ip=192.168.151.13
Tcp2_5_Dup_Id=0
Tcp2_5_Port=13170
Tcp2_End

# 금융파생체결 (TCP)
Tcp2_6_Comment=금융상품파생체결
Tcp2_6_Ip=192.168.151.13
Tcp2_6_Dup_Id=0
Tcp2_6_Port=13171
Tcp2_End

# KRX 주문 (KTS)
Tcp2_7_Comment=체권주문송신01
Tcp2_7_Ip=172.18.120.105
Tcp2_7_Dup_Id=0
Tcp2_7_Port=37221
Tcp2_End

Tcp2_8_Comment=체권주문송신_02_KRX
Tcp2_8_Ip=172.18.120.105
Tcp2_8_Dup_Id=0
Tcp2_8_Port=55556
Tcp2_End

# KRX RDS일괄수신 (KTS)
Tcp2_9_Comment=체권RDS02_KRX
Tcp2_9_Ip=172.18.120.105
Tcp2_9_Dup_Id=0
#Tcp2_9_Port=63725
Tcp2_9_Port=63724
Tcp2_End

# KRX 일괄송신 (KTS)
Tcp2_10_Comment=체권일괄송신_KRX
Tcp2_10_Ip=172.18.120.105
Tcp2_10_Dup_Id=0
#Tcp2_10_Port=63724
Tcp2_10_Port=63725
Tcp2_End

# KRX 체결DropCopy (KTS)
Tcp2_11_Comment=체권체결DC_KRX
Tcp2_11_Ip=172.18.120.105
Tcp2_11_Dup_Id=0
Tcp2_11_Port=61726
Tcp2_End

# KRX 주문 (KTS)
Tcp2_12_Comment=채권응답체결수신01
Tcp2_12_Ip=172.18.120.105
Tcp2_12_Dup_Id=0
Tcp2_12_Port=57221
Tcp2_End

Tcp2_13_Comment=체권주문수신_02_KRX
Tcp2_13_Ip=172.18.120.105
Tcp2_13_Dup_Id=0
Tcp2_13_Port=55558
Tcp2_End

# KRX 채권체결DropCopy (KTS)
Tcp2_14_Comment=채권체결DP
Tcp2_14_Ip=172.18.120.105
Tcp2_14_Dup_Id=0
Tcp2_14_Port=61726
Tcp2_End

# KRX 공개장운영(KTS)
Tcp2_15_Comment=공개장운영_FEP(장운영TEST)
Tcp2_15_Ip=172.18.120.105
Tcp2_15_Dup_Id=0
Tcp2_15_Port=61725
Tcp2_End

Tcp2_16_Comment=Client(송신)SVR
Tcp2_16_Ip=0.0.0.0
Tcp2_16_Dup_Id=0
Tcp2_16_Port=32001
Tcp2_End

Tcp2_17_Comment=채권장운영송신_업무
Tcp2_17_Ip=0.0.0.0
Tcp2_17_Dup_Id=0
Tcp2_17_Port=32008
Tcp2_End

Tcp2_18_Comment=일괄수신결과송신
Tcp2_18_Ip=0.0.0.0
Tcp2_18_Dup_Id=0
Tcp2_18_Port=32016
Tcp2_End

Tcp2_19_Comment=채권RDS01송신_업무
Tcp2_19_Ip=0.0.0.0
Tcp2_19_Dup_Id=0
Tcp2_19_Port=32017
Tcp2_End

Tcp2_20_Comment=채권RDS02송신_업무
Tcp2_20_Ip=0.0.0.0
Tcp2_20_Dup_Id=0
Tcp2_20_Port=32018
Tcp2_End

Tcp2_21_Comment=채권체결DP송신
Tcp2_21_Ip=0.0.0.0
Tcp2_21_Dup_Id=0
Tcp2_21_Port=32009
Tcp2_End

Tcp2_22_Comment=Client(수신)_SVR
Tcp2_22_Ip=0.0.0.0
Tcp2_22_Dup_Id=0
Tcp2_22_Port=32011
Tcp2_End

Tcp2_23_Comment=채권Batch송신_업무계
Tcp2_23_Ip=0.0.0.0
Tcp2_23_Dup_Id=0
Tcp2_23_Port=32019
Tcp2_End

Tcp2_24_Comment=_Client(송신)SVR2
Tcp2_24_Ip=0.0.0.0
Tcp2_24_Dup_Id=0
Tcp2_24_Port=32002
Tcp2_End

Tcp2_25_Comment=_Client(수신)_SVR2
Tcp2_25_Ip=0.0.0.0
Tcp2_25_Dup_Id=0
Tcp2_25_Port=32012
Tcp2_End

Tcp2_26_Comment=IMSI
Tcp2_26_Ip=0.0.0.0
Tcp2_26_Dup_Id=0
Tcp2_26_Port=31000
Tcp2_End

Tcp2_27_Comment=주문송신
Tcp2_27_Ip=0.0.0.0
Tcp2_27_Dup_Id=0
Tcp2_27_Port=41001
Tcp2_End

Tcp2_28_Comment=주문오류수신
Tcp2_28_Ip=0.0.0.0
Tcp2_28_Dup_Id=0
Tcp2_28_Port=41002
Tcp2_End

Tcp2_29_Comment=응답수신
Tcp2_29_Ip=0.0.0.0
Tcp2_29_Dup_Id=0
Tcp2_29_Port=41003
Tcp2_End

Tcp2_30_Comment=공개장운영수신
Tcp2_30_Ip=0.0.0.0
Tcp2_30_Dup_Id=0
Tcp2_30_Port=41004
Tcp2_End

Tcp2_31_Comment=일괄송신_RDS
Tcp2_31_Ip=0.0.0.0
Tcp2_31_Dup_Id=0
Tcp2_31_Port=41005
Tcp2_End

Tcp2_32_Comment=채권체결호가송신
Tcp2_32_Ip=0.0.0.0
Tcp2_32_Dup_Id=0
Tcp2_32_Port=42001
Tcp2_End

Tcp2_33_Comment=채권M4송신
Tcp2_33_Ip=0.0.0.0
Tcp2_33_Dup_Id=0
Tcp2_33_Port=42002
Tcp2_End

Tcp2_34_Comment=채권체결호가송신
Tcp2_34_Ip=0.0.0.0
Tcp2_34_Dup_Id=0
Tcp2_34_Port=16511 
Tcp2_End

PA_CONF_END

##########################################################################
# End of File (tcp2.ini)
##########################################################################
